// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.25.1
// source: device_srv/radar/radar.proto

package device

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetRadarPlotRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetRadarPlotRequest) Reset() {
	*x = GetRadarPlotRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_device_srv_radar_radar_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRadarPlotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRadarPlotRequest) ProtoMessage() {}

func (x *GetRadarPlotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_device_srv_radar_radar_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRadarPlotRequest.ProtoReflect.Descriptor instead.
func (*GetRadarPlotRequest) Descriptor() ([]byte, []int) {
	return file_device_srv_radar_radar_proto_rawDescGZIP(), []int{0}
}

type GetRadarPlotReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetRadarPlotReply) Reset() {
	*x = GetRadarPlotReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_device_srv_radar_radar_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRadarPlotReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRadarPlotReply) ProtoMessage() {}

func (x *GetRadarPlotReply) ProtoReflect() protoreflect.Message {
	mi := &file_device_srv_radar_radar_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRadarPlotReply.ProtoReflect.Descriptor instead.
func (*GetRadarPlotReply) Descriptor() ([]byte, []int) {
	return file_device_srv_radar_radar_proto_rawDescGZIP(), []int{1}
}

type GetRadarTrackRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetRadarTrackRequest) Reset() {
	*x = GetRadarTrackRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_device_srv_radar_radar_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRadarTrackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRadarTrackRequest) ProtoMessage() {}

func (x *GetRadarTrackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_device_srv_radar_radar_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRadarTrackRequest.ProtoReflect.Descriptor instead.
func (*GetRadarTrackRequest) Descriptor() ([]byte, []int) {
	return file_device_srv_radar_radar_proto_rawDescGZIP(), []int{2}
}

type GetRadarTrackReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetRadarTrackReply) Reset() {
	*x = GetRadarTrackReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_device_srv_radar_radar_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRadarTrackReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRadarTrackReply) ProtoMessage() {}

func (x *GetRadarTrackReply) ProtoReflect() protoreflect.Message {
	mi := &file_device_srv_radar_radar_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRadarTrackReply.ProtoReflect.Descriptor instead.
func (*GetRadarTrackReply) Descriptor() ([]byte, []int) {
	return file_device_srv_radar_radar_proto_rawDescGZIP(), []int{3}
}

type CreateRadarRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateRadarRequest) Reset() {
	*x = CreateRadarRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_device_srv_radar_radar_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateRadarRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRadarRequest) ProtoMessage() {}

func (x *CreateRadarRequest) ProtoReflect() protoreflect.Message {
	mi := &file_device_srv_radar_radar_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRadarRequest.ProtoReflect.Descriptor instead.
func (*CreateRadarRequest) Descriptor() ([]byte, []int) {
	return file_device_srv_radar_radar_proto_rawDescGZIP(), []int{4}
}

type CreateRadarReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateRadarReply) Reset() {
	*x = CreateRadarReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_device_srv_radar_radar_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateRadarReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRadarReply) ProtoMessage() {}

func (x *CreateRadarReply) ProtoReflect() protoreflect.Message {
	mi := &file_device_srv_radar_radar_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRadarReply.ProtoReflect.Descriptor instead.
func (*CreateRadarReply) Descriptor() ([]byte, []int) {
	return file_device_srv_radar_radar_proto_rawDescGZIP(), []int{5}
}

type UpdateRadarRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateRadarRequest) Reset() {
	*x = UpdateRadarRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_device_srv_radar_radar_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateRadarRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRadarRequest) ProtoMessage() {}

func (x *UpdateRadarRequest) ProtoReflect() protoreflect.Message {
	mi := &file_device_srv_radar_radar_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRadarRequest.ProtoReflect.Descriptor instead.
func (*UpdateRadarRequest) Descriptor() ([]byte, []int) {
	return file_device_srv_radar_radar_proto_rawDescGZIP(), []int{6}
}

type UpdateRadarReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateRadarReply) Reset() {
	*x = UpdateRadarReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_device_srv_radar_radar_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateRadarReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRadarReply) ProtoMessage() {}

func (x *UpdateRadarReply) ProtoReflect() protoreflect.Message {
	mi := &file_device_srv_radar_radar_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRadarReply.ProtoReflect.Descriptor instead.
func (*UpdateRadarReply) Descriptor() ([]byte, []int) {
	return file_device_srv_radar_radar_proto_rawDescGZIP(), []int{7}
}

type DeleteRadarRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteRadarRequest) Reset() {
	*x = DeleteRadarRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_device_srv_radar_radar_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteRadarRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRadarRequest) ProtoMessage() {}

func (x *DeleteRadarRequest) ProtoReflect() protoreflect.Message {
	mi := &file_device_srv_radar_radar_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRadarRequest.ProtoReflect.Descriptor instead.
func (*DeleteRadarRequest) Descriptor() ([]byte, []int) {
	return file_device_srv_radar_radar_proto_rawDescGZIP(), []int{8}
}

type DeleteRadarReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteRadarReply) Reset() {
	*x = DeleteRadarReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_device_srv_radar_radar_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteRadarReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRadarReply) ProtoMessage() {}

func (x *DeleteRadarReply) ProtoReflect() protoreflect.Message {
	mi := &file_device_srv_radar_radar_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRadarReply.ProtoReflect.Descriptor instead.
func (*DeleteRadarReply) Descriptor() ([]byte, []int) {
	return file_device_srv_radar_radar_proto_rawDescGZIP(), []int{9}
}

type GetRadarStatusRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetRadarStatusRequest) Reset() {
	*x = GetRadarStatusRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_device_srv_radar_radar_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRadarStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRadarStatusRequest) ProtoMessage() {}

func (x *GetRadarStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_device_srv_radar_radar_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRadarStatusRequest.ProtoReflect.Descriptor instead.
func (*GetRadarStatusRequest) Descriptor() ([]byte, []int) {
	return file_device_srv_radar_radar_proto_rawDescGZIP(), []int{10}
}

type GetRadarStatusReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetRadarStatusReply) Reset() {
	*x = GetRadarStatusReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_device_srv_radar_radar_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRadarStatusReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRadarStatusReply) ProtoMessage() {}

func (x *GetRadarStatusReply) ProtoReflect() protoreflect.Message {
	mi := &file_device_srv_radar_radar_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRadarStatusReply.ProtoReflect.Descriptor instead.
func (*GetRadarStatusReply) Descriptor() ([]byte, []int) {
	return file_device_srv_radar_radar_proto_rawDescGZIP(), []int{11}
}

type ListRadarRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListRadarRequest) Reset() {
	*x = ListRadarRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_device_srv_radar_radar_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListRadarRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRadarRequest) ProtoMessage() {}

func (x *ListRadarRequest) ProtoReflect() protoreflect.Message {
	mi := &file_device_srv_radar_radar_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRadarRequest.ProtoReflect.Descriptor instead.
func (*ListRadarRequest) Descriptor() ([]byte, []int) {
	return file_device_srv_radar_radar_proto_rawDescGZIP(), []int{12}
}

type ListRadarReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListRadarReply) Reset() {
	*x = ListRadarReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_device_srv_radar_radar_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListRadarReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRadarReply) ProtoMessage() {}

func (x *ListRadarReply) ProtoReflect() protoreflect.Message {
	mi := &file_device_srv_radar_radar_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRadarReply.ProtoReflect.Descriptor instead.
func (*ListRadarReply) Descriptor() ([]byte, []int) {
	return file_device_srv_radar_radar_proto_rawDescGZIP(), []int{13}
}

type RadarPlot struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlotNumber         uint32  `protobuf:"varint,1,opt,name=plot_number,json=plotNumber,proto3" json:"plot_number,omitempty"`
	PlotAzimuth        float32 `protobuf:"fixed32,2,opt,name=plot_azimuth,json=plotAzimuth,proto3" json:"plot_azimuth,omitempty"`
	PlotDistance       float32 `protobuf:"fixed32,3,opt,name=plot_distance,json=plotDistance,proto3" json:"plot_distance,omitempty"`
	PlotAltitude       float32 `protobuf:"fixed32,4,opt,name=plot_altitude,json=plotAltitude,proto3" json:"plot_altitude,omitempty"`
	RadialVelocity     float32 `protobuf:"fixed32,5,opt,name=radial_velocity,json=radialVelocity,proto3" json:"radial_velocity,omitempty"`
	TangentialVelocity float32 `protobuf:"fixed32,6,opt,name=tangential_velocity,json=tangentialVelocity,proto3" json:"tangential_velocity,omitempty"`
	PlotMode           uint32  `protobuf:"varint,7,opt,name=plot_mode,json=plotMode,proto3" json:"plot_mode,omitempty"`
	PlotTypeSupplement uint32  `protobuf:"varint,8,opt,name=plot_type_supplement,json=plotTypeSupplement,proto3" json:"plot_type_supplement,omitempty"`
	PlotType           uint32  `protobuf:"varint,9,opt,name=plot_type,json=plotType,proto3" json:"plot_type,omitempty"`
	PlotRcs            float32 `protobuf:"fixed32,10,opt,name=plot_rcs,json=plotRcs,proto3" json:"plot_rcs,omitempty"`
	HoverStatus        uint32  `protobuf:"varint,11,opt,name=hover_status,json=hoverStatus,proto3" json:"hover_status,omitempty"`
	PlotReserved       uint32  `protobuf:"varint,12,opt,name=plot_reserved,json=plotReserved,proto3" json:"plot_reserved,omitempty"`
}

func (x *RadarPlot) Reset() {
	*x = RadarPlot{}
	if protoimpl.UnsafeEnabled {
		mi := &file_device_srv_radar_radar_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RadarPlot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RadarPlot) ProtoMessage() {}

func (x *RadarPlot) ProtoReflect() protoreflect.Message {
	mi := &file_device_srv_radar_radar_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RadarPlot.ProtoReflect.Descriptor instead.
func (*RadarPlot) Descriptor() ([]byte, []int) {
	return file_device_srv_radar_radar_proto_rawDescGZIP(), []int{14}
}

func (x *RadarPlot) GetPlotNumber() uint32 {
	if x != nil {
		return x.PlotNumber
	}
	return 0
}

func (x *RadarPlot) GetPlotAzimuth() float32 {
	if x != nil {
		return x.PlotAzimuth
	}
	return 0
}

func (x *RadarPlot) GetPlotDistance() float32 {
	if x != nil {
		return x.PlotDistance
	}
	return 0
}

func (x *RadarPlot) GetPlotAltitude() float32 {
	if x != nil {
		return x.PlotAltitude
	}
	return 0
}

func (x *RadarPlot) GetRadialVelocity() float32 {
	if x != nil {
		return x.RadialVelocity
	}
	return 0
}

func (x *RadarPlot) GetTangentialVelocity() float32 {
	if x != nil {
		return x.TangentialVelocity
	}
	return 0
}

func (x *RadarPlot) GetPlotMode() uint32 {
	if x != nil {
		return x.PlotMode
	}
	return 0
}

func (x *RadarPlot) GetPlotTypeSupplement() uint32 {
	if x != nil {
		return x.PlotTypeSupplement
	}
	return 0
}

func (x *RadarPlot) GetPlotType() uint32 {
	if x != nil {
		return x.PlotType
	}
	return 0
}

func (x *RadarPlot) GetPlotRcs() float32 {
	if x != nil {
		return x.PlotRcs
	}
	return 0
}

func (x *RadarPlot) GetHoverStatus() uint32 {
	if x != nil {
		return x.HoverStatus
	}
	return 0
}

func (x *RadarPlot) GetPlotReserved() uint32 {
	if x != nil {
		return x.PlotReserved
	}
	return 0
}

var File_device_srv_radar_radar_proto protoreflect.FileDescriptor

var file_device_srv_radar_radar_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x73, 0x72, 0x76, 0x2f, 0x72, 0x61, 0x64,
	0x61, 0x72, 0x2f, 0x72, 0x61, 0x64, 0x61, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x14,
	0x62, 0x69, 0x7a, 0x2e, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x73, 0x72, 0x76, 0x2e, 0x72,
	0x61, 0x64, 0x61, 0x72, 0x22, 0x15, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x52, 0x61, 0x64, 0x61, 0x72,
	0x50, 0x6c, 0x6f, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x13, 0x0a, 0x11, 0x47,
	0x65, 0x74, 0x52, 0x61, 0x64, 0x61, 0x72, 0x50, 0x6c, 0x6f, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x22, 0x16, 0x0a, 0x14, 0x67, 0x65, 0x74, 0x52, 0x61, 0x64, 0x61, 0x72, 0x54, 0x72, 0x61, 0x63,
	0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x14, 0x0a, 0x12, 0x67, 0x65, 0x74, 0x52,
	0x61, 0x64, 0x61, 0x72, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x14,
	0x0a, 0x12, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x61, 0x64, 0x61, 0x72, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x22, 0x12, 0x0a, 0x10, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x61,
	0x64, 0x61, 0x72, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x14, 0x0a, 0x12, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x52, 0x61, 0x64, 0x61, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x12,
	0x0a, 0x10, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x61, 0x64, 0x61, 0x72, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x22, 0x14, 0x0a, 0x12, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x61, 0x64, 0x61,
	0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x12, 0x0a, 0x10, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x52, 0x61, 0x64, 0x61, 0x72, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x17, 0x0a, 0x15,
	0x47, 0x65, 0x74, 0x52, 0x61, 0x64, 0x61, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x15, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x52, 0x61, 0x64, 0x61,
	0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x12, 0x0a, 0x10,
	0x4c, 0x69, 0x73, 0x74, 0x52, 0x61, 0x64, 0x61, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x22, 0x10, 0x0a, 0x0e, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x61, 0x64, 0x61, 0x72, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x22, 0xc2, 0x03, 0x0a, 0x09, 0x52, 0x61, 0x64, 0x61, 0x72, 0x50, 0x6c, 0x6f, 0x74,
	0x12, 0x1f, 0x0a, 0x0b, 0x70, 0x6c, 0x6f, 0x74, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x70, 0x6c, 0x6f, 0x74, 0x4e, 0x75, 0x6d, 0x62, 0x65,
	0x72, 0x12, 0x21, 0x0a, 0x0c, 0x70, 0x6c, 0x6f, 0x74, 0x5f, 0x61, 0x7a, 0x69, 0x6d, 0x75, 0x74,
	0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0b, 0x70, 0x6c, 0x6f, 0x74, 0x41, 0x7a, 0x69,
	0x6d, 0x75, 0x74, 0x68, 0x12, 0x23, 0x0a, 0x0d, 0x70, 0x6c, 0x6f, 0x74, 0x5f, 0x64, 0x69, 0x73,
	0x74, 0x61, 0x6e, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0c, 0x70, 0x6c, 0x6f,
	0x74, 0x44, 0x69, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x70, 0x6c, 0x6f,
	0x74, 0x5f, 0x61, 0x6c, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x02,
	0x52, 0x0c, 0x70, 0x6c, 0x6f, 0x74, 0x41, 0x6c, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x12, 0x27,
	0x0a, 0x0f, 0x72, 0x61, 0x64, 0x69, 0x61, 0x6c, 0x5f, 0x76, 0x65, 0x6c, 0x6f, 0x63, 0x69, 0x74,
	0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0e, 0x72, 0x61, 0x64, 0x69, 0x61, 0x6c, 0x56,
	0x65, 0x6c, 0x6f, 0x63, 0x69, 0x74, 0x79, 0x12, 0x2f, 0x0a, 0x13, 0x74, 0x61, 0x6e, 0x67, 0x65,
	0x6e, 0x74, 0x69, 0x61, 0x6c, 0x5f, 0x76, 0x65, 0x6c, 0x6f, 0x63, 0x69, 0x74, 0x79, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x02, 0x52, 0x12, 0x74, 0x61, 0x6e, 0x67, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c,
	0x56, 0x65, 0x6c, 0x6f, 0x63, 0x69, 0x74, 0x79, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x6c, 0x6f, 0x74,
	0x5f, 0x6d, 0x6f, 0x64, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x70, 0x6c, 0x6f,
	0x74, 0x4d, 0x6f, 0x64, 0x65, 0x12, 0x30, 0x0a, 0x14, 0x70, 0x6c, 0x6f, 0x74, 0x5f, 0x74, 0x79,
	0x70, 0x65, 0x5f, 0x73, 0x75, 0x70, 0x70, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x08, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x12, 0x70, 0x6c, 0x6f, 0x74, 0x54, 0x79, 0x70, 0x65, 0x53, 0x75, 0x70,
	0x70, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x6c, 0x6f, 0x74, 0x5f,
	0x74, 0x79, 0x70, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x70, 0x6c, 0x6f, 0x74,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x70, 0x6c, 0x6f, 0x74, 0x5f, 0x72, 0x63, 0x73,
	0x18, 0x0a, 0x20, 0x01, 0x28, 0x02, 0x52, 0x07, 0x70, 0x6c, 0x6f, 0x74, 0x52, 0x63, 0x73, 0x12,
	0x21, 0x0a, 0x0c, 0x68, 0x6f, 0x76, 0x65, 0x72, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18,
	0x0b, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x68, 0x6f, 0x76, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x12, 0x23, 0x0a, 0x0d, 0x70, 0x6c, 0x6f, 0x74, 0x5f, 0x72, 0x65, 0x73, 0x65, 0x72,
	0x76, 0x65, 0x64, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0c, 0x70, 0x6c, 0x6f, 0x74, 0x52,
	0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x64, 0x32, 0xc6, 0x05, 0x0a, 0x05, 0x52, 0x61, 0x64, 0x61,
	0x72, 0x12, 0x5f, 0x0a, 0x0b, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x61, 0x64, 0x61, 0x72,
	0x12, 0x28, 0x2e, 0x62, 0x69, 0x7a, 0x2e, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x73, 0x72,
	0x76, 0x2e, 0x72, 0x61, 0x64, 0x61, 0x72, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x61,
	0x64, 0x61, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x26, 0x2e, 0x62, 0x69, 0x7a,
	0x2e, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x73, 0x72, 0x76, 0x2e, 0x72, 0x61, 0x64, 0x61,
	0x72, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x61, 0x64, 0x61, 0x72, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x12, 0x5f, 0x0a, 0x0b, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x61, 0x64, 0x61,
	0x72, 0x12, 0x28, 0x2e, 0x62, 0x69, 0x7a, 0x2e, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x73,
	0x72, 0x76, 0x2e, 0x72, 0x61, 0x64, 0x61, 0x72, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52,
	0x61, 0x64, 0x61, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x26, 0x2e, 0x62, 0x69,
	0x7a, 0x2e, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x73, 0x72, 0x76, 0x2e, 0x72, 0x61, 0x64,
	0x61, 0x72, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x61, 0x64, 0x61, 0x72, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x12, 0x5f, 0x0a, 0x0b, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x61, 0x64,
	0x61, 0x72, 0x12, 0x28, 0x2e, 0x62, 0x69, 0x7a, 0x2e, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x5f,
	0x73, 0x72, 0x76, 0x2e, 0x72, 0x61, 0x64, 0x61, 0x72, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x52, 0x61, 0x64, 0x61, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x26, 0x2e, 0x62,
	0x69, 0x7a, 0x2e, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x73, 0x72, 0x76, 0x2e, 0x72, 0x61,
	0x64, 0x61, 0x72, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x61, 0x64, 0x61, 0x72, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x12, 0x59, 0x0a, 0x09, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x61, 0x64, 0x61,
	0x72, 0x12, 0x26, 0x2e, 0x62, 0x69, 0x7a, 0x2e, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x73,
	0x72, 0x76, 0x2e, 0x72, 0x61, 0x64, 0x61, 0x72, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x61, 0x64,
	0x61, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x62, 0x69, 0x7a, 0x2e,
	0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x73, 0x72, 0x76, 0x2e, 0x72, 0x61, 0x64, 0x61, 0x72,
	0x2e, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x61, 0x64, 0x61, 0x72, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12,
	0x6c, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x52, 0x61, 0x64, 0x61, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x12, 0x2b, 0x2e, 0x62, 0x69, 0x7a, 0x2e, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x73,
	0x72, 0x76, 0x2e, 0x72, 0x61, 0x64, 0x61, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x61, 0x64, 0x61,
	0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x29,
	0x2e, 0x62, 0x69, 0x7a, 0x2e, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x73, 0x72, 0x76, 0x2e,
	0x72, 0x61, 0x64, 0x61, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x61, 0x64, 0x61, 0x72, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x28, 0x01, 0x30, 0x01, 0x12, 0x69, 0x0a,
	0x0d, 0x67, 0x65, 0x74, 0x52, 0x61, 0x64, 0x61, 0x72, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x12, 0x2a,
	0x2e, 0x62, 0x69, 0x7a, 0x2e, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x73, 0x72, 0x76, 0x2e,
	0x72, 0x61, 0x64, 0x61, 0x72, 0x2e, 0x67, 0x65, 0x74, 0x52, 0x61, 0x64, 0x61, 0x72, 0x54, 0x72,
	0x61, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x28, 0x2e, 0x62, 0x69, 0x7a,
	0x2e, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x73, 0x72, 0x76, 0x2e, 0x72, 0x61, 0x64, 0x61,
	0x72, 0x2e, 0x67, 0x65, 0x74, 0x52, 0x61, 0x64, 0x61, 0x72, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x28, 0x01, 0x30, 0x01, 0x12, 0x66, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x52,
	0x61, 0x64, 0x61, 0x72, 0x50, 0x6c, 0x6f, 0x74, 0x12, 0x29, 0x2e, 0x62, 0x69, 0x7a, 0x2e, 0x64,
	0x65, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x73, 0x72, 0x76, 0x2e, 0x72, 0x61, 0x64, 0x61, 0x72, 0x2e,
	0x47, 0x65, 0x74, 0x52, 0x61, 0x64, 0x61, 0x72, 0x50, 0x6c, 0x6f, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x27, 0x2e, 0x62, 0x69, 0x7a, 0x2e, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65,
	0x5f, 0x73, 0x72, 0x76, 0x2e, 0x72, 0x61, 0x64, 0x61, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x61,
	0x64, 0x61, 0x72, 0x50, 0x6c, 0x6f, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x28, 0x01, 0x30, 0x01,
	0x42, 0x2a, 0x0a, 0x0a, 0x61, 0x70, 0x69, 0x2e, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x50, 0x01,
	0x5a, 0x1a, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x52, 0x65, 0x70, 0x6f, 0x2f, 0x70, 0x62, 0x2f, 0x64,
	0x65, 0x76, 0x69, 0x63, 0x65, 0x3b, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_device_srv_radar_radar_proto_rawDescOnce sync.Once
	file_device_srv_radar_radar_proto_rawDescData = file_device_srv_radar_radar_proto_rawDesc
)

func file_device_srv_radar_radar_proto_rawDescGZIP() []byte {
	file_device_srv_radar_radar_proto_rawDescOnce.Do(func() {
		file_device_srv_radar_radar_proto_rawDescData = protoimpl.X.CompressGZIP(file_device_srv_radar_radar_proto_rawDescData)
	})
	return file_device_srv_radar_radar_proto_rawDescData
}

var file_device_srv_radar_radar_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_device_srv_radar_radar_proto_goTypes = []interface{}{
	(*GetRadarPlotRequest)(nil),   // 0: biz.device_srv.radar.GetRadarPlotRequest
	(*GetRadarPlotReply)(nil),     // 1: biz.device_srv.radar.GetRadarPlotReply
	(*GetRadarTrackRequest)(nil),  // 2: biz.device_srv.radar.getRadarTrackRequest
	(*GetRadarTrackReply)(nil),    // 3: biz.device_srv.radar.getRadarTrackReply
	(*CreateRadarRequest)(nil),    // 4: biz.device_srv.radar.CreateRadarRequest
	(*CreateRadarReply)(nil),      // 5: biz.device_srv.radar.CreateRadarReply
	(*UpdateRadarRequest)(nil),    // 6: biz.device_srv.radar.UpdateRadarRequest
	(*UpdateRadarReply)(nil),      // 7: biz.device_srv.radar.UpdateRadarReply
	(*DeleteRadarRequest)(nil),    // 8: biz.device_srv.radar.DeleteRadarRequest
	(*DeleteRadarReply)(nil),      // 9: biz.device_srv.radar.DeleteRadarReply
	(*GetRadarStatusRequest)(nil), // 10: biz.device_srv.radar.GetRadarStatusRequest
	(*GetRadarStatusReply)(nil),   // 11: biz.device_srv.radar.GetRadarStatusReply
	(*ListRadarRequest)(nil),      // 12: biz.device_srv.radar.ListRadarRequest
	(*ListRadarReply)(nil),        // 13: biz.device_srv.radar.ListRadarReply
	(*RadarPlot)(nil),             // 14: biz.device_srv.radar.RadarPlot
}
var file_device_srv_radar_radar_proto_depIdxs = []int32{
	4,  // 0: biz.device_srv.radar.Radar.CreateRadar:input_type -> biz.device_srv.radar.CreateRadarRequest
	6,  // 1: biz.device_srv.radar.Radar.UpdateRadar:input_type -> biz.device_srv.radar.UpdateRadarRequest
	8,  // 2: biz.device_srv.radar.Radar.DeleteRadar:input_type -> biz.device_srv.radar.DeleteRadarRequest
	12, // 3: biz.device_srv.radar.Radar.ListRadar:input_type -> biz.device_srv.radar.ListRadarRequest
	10, // 4: biz.device_srv.radar.Radar.GetRadarStatus:input_type -> biz.device_srv.radar.GetRadarStatusRequest
	2,  // 5: biz.device_srv.radar.Radar.getRadarTrack:input_type -> biz.device_srv.radar.getRadarTrackRequest
	0,  // 6: biz.device_srv.radar.Radar.GetRadarPlot:input_type -> biz.device_srv.radar.GetRadarPlotRequest
	5,  // 7: biz.device_srv.radar.Radar.CreateRadar:output_type -> biz.device_srv.radar.CreateRadarReply
	7,  // 8: biz.device_srv.radar.Radar.UpdateRadar:output_type -> biz.device_srv.radar.UpdateRadarReply
	9,  // 9: biz.device_srv.radar.Radar.DeleteRadar:output_type -> biz.device_srv.radar.DeleteRadarReply
	13, // 10: biz.device_srv.radar.Radar.ListRadar:output_type -> biz.device_srv.radar.ListRadarReply
	11, // 11: biz.device_srv.radar.Radar.GetRadarStatus:output_type -> biz.device_srv.radar.GetRadarStatusReply
	3,  // 12: biz.device_srv.radar.Radar.getRadarTrack:output_type -> biz.device_srv.radar.getRadarTrackReply
	1,  // 13: biz.device_srv.radar.Radar.GetRadarPlot:output_type -> biz.device_srv.radar.GetRadarPlotReply
	7,  // [7:14] is the sub-list for method output_type
	0,  // [0:7] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_device_srv_radar_radar_proto_init() }
func file_device_srv_radar_radar_proto_init() {
	if File_device_srv_radar_radar_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_device_srv_radar_radar_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRadarPlotRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_device_srv_radar_radar_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRadarPlotReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_device_srv_radar_radar_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRadarTrackRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_device_srv_radar_radar_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRadarTrackReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_device_srv_radar_radar_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateRadarRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_device_srv_radar_radar_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateRadarReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_device_srv_radar_radar_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateRadarRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_device_srv_radar_radar_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateRadarReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_device_srv_radar_radar_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteRadarRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_device_srv_radar_radar_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteRadarReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_device_srv_radar_radar_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRadarStatusRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_device_srv_radar_radar_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRadarStatusReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_device_srv_radar_radar_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListRadarRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_device_srv_radar_radar_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListRadarReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_device_srv_radar_radar_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RadarPlot); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_device_srv_radar_radar_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_device_srv_radar_radar_proto_goTypes,
		DependencyIndexes: file_device_srv_radar_radar_proto_depIdxs,
		MessageInfos:      file_device_srv_radar_radar_proto_msgTypes,
	}.Build()
	File_device_srv_radar_radar_proto = out.File
	file_device_srv_radar_radar_proto_rawDesc = nil
	file_device_srv_radar_radar_proto_goTypes = nil
	file_device_srv_radar_radar_proto_depIdxs = nil
}
