// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.25.1
// source: bird_ai_bird/detect/detect.proto

package detect

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateDetectRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateDetectRequest) Reset() {
	*x = CreateDetectRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bird_ai_bird_detect_detect_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateDetectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDetectRequest) ProtoMessage() {}

func (x *CreateDetectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bird_ai_bird_detect_detect_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDetectRequest.ProtoReflect.Descriptor instead.
func (*CreateDetectRequest) Descriptor() ([]byte, []int) {
	return file_bird_ai_bird_detect_detect_proto_rawDescGZIP(), []int{0}
}

type CreateDetectReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateDetectReply) Reset() {
	*x = CreateDetectReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bird_ai_bird_detect_detect_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateDetectReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDetectReply) ProtoMessage() {}

func (x *CreateDetectReply) ProtoReflect() protoreflect.Message {
	mi := &file_bird_ai_bird_detect_detect_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDetectReply.ProtoReflect.Descriptor instead.
func (*CreateDetectReply) Descriptor() ([]byte, []int) {
	return file_bird_ai_bird_detect_detect_proto_rawDescGZIP(), []int{1}
}

type UpdateDetectRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateDetectRequest) Reset() {
	*x = UpdateDetectRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bird_ai_bird_detect_detect_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateDetectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDetectRequest) ProtoMessage() {}

func (x *UpdateDetectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bird_ai_bird_detect_detect_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDetectRequest.ProtoReflect.Descriptor instead.
func (*UpdateDetectRequest) Descriptor() ([]byte, []int) {
	return file_bird_ai_bird_detect_detect_proto_rawDescGZIP(), []int{2}
}

type UpdateDetectReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateDetectReply) Reset() {
	*x = UpdateDetectReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bird_ai_bird_detect_detect_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateDetectReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDetectReply) ProtoMessage() {}

func (x *UpdateDetectReply) ProtoReflect() protoreflect.Message {
	mi := &file_bird_ai_bird_detect_detect_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDetectReply.ProtoReflect.Descriptor instead.
func (*UpdateDetectReply) Descriptor() ([]byte, []int) {
	return file_bird_ai_bird_detect_detect_proto_rawDescGZIP(), []int{3}
}

type DeleteDetectRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteDetectRequest) Reset() {
	*x = DeleteDetectRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bird_ai_bird_detect_detect_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteDetectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDetectRequest) ProtoMessage() {}

func (x *DeleteDetectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bird_ai_bird_detect_detect_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDetectRequest.ProtoReflect.Descriptor instead.
func (*DeleteDetectRequest) Descriptor() ([]byte, []int) {
	return file_bird_ai_bird_detect_detect_proto_rawDescGZIP(), []int{4}
}

type DeleteDetectReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteDetectReply) Reset() {
	*x = DeleteDetectReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bird_ai_bird_detect_detect_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteDetectReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDetectReply) ProtoMessage() {}

func (x *DeleteDetectReply) ProtoReflect() protoreflect.Message {
	mi := &file_bird_ai_bird_detect_detect_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDetectReply.ProtoReflect.Descriptor instead.
func (*DeleteDetectReply) Descriptor() ([]byte, []int) {
	return file_bird_ai_bird_detect_detect_proto_rawDescGZIP(), []int{5}
}

type GetDetectRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetDetectRequest) Reset() {
	*x = GetDetectRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bird_ai_bird_detect_detect_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDetectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDetectRequest) ProtoMessage() {}

func (x *GetDetectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bird_ai_bird_detect_detect_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDetectRequest.ProtoReflect.Descriptor instead.
func (*GetDetectRequest) Descriptor() ([]byte, []int) {
	return file_bird_ai_bird_detect_detect_proto_rawDescGZIP(), []int{6}
}

type GetDetectReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetDetectReply) Reset() {
	*x = GetDetectReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bird_ai_bird_detect_detect_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDetectReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDetectReply) ProtoMessage() {}

func (x *GetDetectReply) ProtoReflect() protoreflect.Message {
	mi := &file_bird_ai_bird_detect_detect_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDetectReply.ProtoReflect.Descriptor instead.
func (*GetDetectReply) Descriptor() ([]byte, []int) {
	return file_bird_ai_bird_detect_detect_proto_rawDescGZIP(), []int{7}
}

type ListDetectRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListDetectRequest) Reset() {
	*x = ListDetectRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bird_ai_bird_detect_detect_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListDetectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDetectRequest) ProtoMessage() {}

func (x *ListDetectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bird_ai_bird_detect_detect_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDetectRequest.ProtoReflect.Descriptor instead.
func (*ListDetectRequest) Descriptor() ([]byte, []int) {
	return file_bird_ai_bird_detect_detect_proto_rawDescGZIP(), []int{8}
}

type ListDetectReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListDetectReply) Reset() {
	*x = ListDetectReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bird_ai_bird_detect_detect_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListDetectReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDetectReply) ProtoMessage() {}

func (x *ListDetectReply) ProtoReflect() protoreflect.Message {
	mi := &file_bird_ai_bird_detect_detect_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDetectReply.ProtoReflect.Descriptor instead.
func (*ListDetectReply) Descriptor() ([]byte, []int) {
	return file_bird_ai_bird_detect_detect_proto_rawDescGZIP(), []int{9}
}

type DetectionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PicPath string `protobuf:"bytes,1,opt,name=picPath,proto3" json:"picPath,omitempty"`
}

func (x *DetectionRequest) Reset() {
	*x = DetectionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bird_ai_bird_detect_detect_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DetectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetectionRequest) ProtoMessage() {}

func (x *DetectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bird_ai_bird_detect_detect_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetectionRequest.ProtoReflect.Descriptor instead.
func (*DetectionRequest) Descriptor() ([]byte, []int) {
	return file_bird_ai_bird_detect_detect_proto_rawDescGZIP(), []int{10}
}

func (x *DetectionRequest) GetPicPath() string {
	if x != nil {
		return x.PicPath
	}
	return ""
}

type DetectionReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result     string `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`         // result true 存在 false 不存在
	ResPath    string `protobuf:"bytes,2,opt,name=resPath,proto3" json:"resPath,omitempty"`       // 检测结果的路径
	ClassId    string `protobuf:"bytes,3,opt,name=classId,proto3" json:"classId,omitempty"`       // 类型id
	ClassName  string `protobuf:"bytes,4,opt,name=className,proto3" json:"className,omitempty"`   // 类型名称
	Confidence string `protobuf:"bytes,5,opt,name=confidence,proto3" json:"confidence,omitempty"` // 置信度
}

func (x *DetectionReply) Reset() {
	*x = DetectionReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bird_ai_bird_detect_detect_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DetectionReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetectionReply) ProtoMessage() {}

func (x *DetectionReply) ProtoReflect() protoreflect.Message {
	mi := &file_bird_ai_bird_detect_detect_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetectionReply.ProtoReflect.Descriptor instead.
func (*DetectionReply) Descriptor() ([]byte, []int) {
	return file_bird_ai_bird_detect_detect_proto_rawDescGZIP(), []int{11}
}

func (x *DetectionReply) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *DetectionReply) GetResPath() string {
	if x != nil {
		return x.ResPath
	}
	return ""
}

func (x *DetectionReply) GetClassId() string {
	if x != nil {
		return x.ClassId
	}
	return ""
}

func (x *DetectionReply) GetClassName() string {
	if x != nil {
		return x.ClassName
	}
	return ""
}

func (x *DetectionReply) GetConfidence() string {
	if x != nil {
		return x.Confidence
	}
	return ""
}

var File_bird_ai_bird_detect_detect_proto protoreflect.FileDescriptor

var file_bird_ai_bird_detect_detect_proto_rawDesc = []byte{
	0x0a, 0x20, 0x62, 0x69, 0x72, 0x64, 0x5f, 0x61, 0x69, 0x5f, 0x62, 0x69, 0x72, 0x64, 0x2f, 0x64,
	0x65, 0x74, 0x65, 0x63, 0x74, 0x2f, 0x64, 0x65, 0x74, 0x65, 0x63, 0x74, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x16, 0x62, 0x69, 0x7a, 0x2e, 0x62, 0x69, 0x72, 0x64, 0x5f, 0x61, 0x69, 0x5f,
	0x73, 0x72, 0x76, 0x2e, 0x64, 0x65, 0x74, 0x65, 0x63, 0x74, 0x22, 0x15, 0x0a, 0x13, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x44, 0x65, 0x74, 0x65, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x22, 0x13, 0x0a, 0x11, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x44, 0x65, 0x74, 0x65, 0x63,
	0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x15, 0x0a, 0x13, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x44, 0x65, 0x74, 0x65, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x13, 0x0a,
	0x11, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x44, 0x65, 0x74, 0x65, 0x63, 0x74, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x22, 0x15, 0x0a, 0x13, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x44, 0x65, 0x74, 0x65,
	0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x13, 0x0a, 0x11, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x44, 0x65, 0x74, 0x65, 0x63, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x12,
	0x0a, 0x10, 0x47, 0x65, 0x74, 0x44, 0x65, 0x74, 0x65, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x22, 0x10, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x44, 0x65, 0x74, 0x65, 0x63, 0x74, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x22, 0x13, 0x0a, 0x11, 0x4c, 0x69, 0x73, 0x74, 0x44, 0x65, 0x74, 0x65,
	0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x11, 0x0a, 0x0f, 0x4c, 0x69, 0x73,
	0x74, 0x44, 0x65, 0x74, 0x65, 0x63, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x2c, 0x0a, 0x10,
	0x44, 0x65, 0x74, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x18, 0x0a, 0x07, 0x70, 0x69, 0x63, 0x50, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x70, 0x69, 0x63, 0x50, 0x61, 0x74, 0x68, 0x22, 0x9a, 0x01, 0x0a, 0x0e, 0x44,
	0x65, 0x74, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x16, 0x0a,
	0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x65, 0x73, 0x50, 0x61, 0x74, 0x68,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x72, 0x65, 0x73, 0x50, 0x61, 0x74, 0x68, 0x12,
	0x18, 0x0a, 0x07, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x6c, 0x61,
	0x73, 0x73, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x6c,
	0x61, 0x73, 0x73, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x6f, 0x6e, 0x66, 0x69,
	0x64, 0x65, 0x6e, 0x63, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x6f, 0x6e,
	0x66, 0x69, 0x64, 0x65, 0x6e, 0x63, 0x65, 0x32, 0xe2, 0x04, 0x0a, 0x06, 0x44, 0x65, 0x74, 0x65,
	0x63, 0x74, 0x12, 0x66, 0x0a, 0x0c, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x44, 0x65, 0x74, 0x65,
	0x63, 0x74, 0x12, 0x2b, 0x2e, 0x62, 0x69, 0x7a, 0x2e, 0x62, 0x69, 0x72, 0x64, 0x5f, 0x61, 0x69,
	0x5f, 0x73, 0x72, 0x76, 0x2e, 0x64, 0x65, 0x74, 0x65, 0x63, 0x74, 0x2e, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x44, 0x65, 0x74, 0x65, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x29, 0x2e, 0x62, 0x69, 0x7a, 0x2e, 0x62, 0x69, 0x72, 0x64, 0x5f, 0x61, 0x69, 0x5f, 0x73, 0x72,
	0x76, 0x2e, 0x64, 0x65, 0x74, 0x65, 0x63, 0x74, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x44,
	0x65, 0x74, 0x65, 0x63, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x66, 0x0a, 0x0c, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x44, 0x65, 0x74, 0x65, 0x63, 0x74, 0x12, 0x2b, 0x2e, 0x62, 0x69, 0x7a,
	0x2e, 0x62, 0x69, 0x72, 0x64, 0x5f, 0x61, 0x69, 0x5f, 0x73, 0x72, 0x76, 0x2e, 0x64, 0x65, 0x74,
	0x65, 0x63, 0x74, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x44, 0x65, 0x74, 0x65, 0x63, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x29, 0x2e, 0x62, 0x69, 0x7a, 0x2e, 0x62, 0x69,
	0x72, 0x64, 0x5f, 0x61, 0x69, 0x5f, 0x73, 0x72, 0x76, 0x2e, 0x64, 0x65, 0x74, 0x65, 0x63, 0x74,
	0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x44, 0x65, 0x74, 0x65, 0x63, 0x74, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x12, 0x66, 0x0a, 0x0c, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x44, 0x65, 0x74, 0x65,
	0x63, 0x74, 0x12, 0x2b, 0x2e, 0x62, 0x69, 0x7a, 0x2e, 0x62, 0x69, 0x72, 0x64, 0x5f, 0x61, 0x69,
	0x5f, 0x73, 0x72, 0x76, 0x2e, 0x64, 0x65, 0x74, 0x65, 0x63, 0x74, 0x2e, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x44, 0x65, 0x74, 0x65, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x29, 0x2e, 0x62, 0x69, 0x7a, 0x2e, 0x62, 0x69, 0x72, 0x64, 0x5f, 0x61, 0x69, 0x5f, 0x73, 0x72,
	0x76, 0x2e, 0x64, 0x65, 0x74, 0x65, 0x63, 0x74, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x44,
	0x65, 0x74, 0x65, 0x63, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x5d, 0x0a, 0x09, 0x47, 0x65,
	0x74, 0x44, 0x65, 0x74, 0x65, 0x63, 0x74, 0x12, 0x28, 0x2e, 0x62, 0x69, 0x7a, 0x2e, 0x62, 0x69,
	0x72, 0x64, 0x5f, 0x61, 0x69, 0x5f, 0x73, 0x72, 0x76, 0x2e, 0x64, 0x65, 0x74, 0x65, 0x63, 0x74,
	0x2e, 0x47, 0x65, 0x74, 0x44, 0x65, 0x74, 0x65, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x26, 0x2e, 0x62, 0x69, 0x7a, 0x2e, 0x62, 0x69, 0x72, 0x64, 0x5f, 0x61, 0x69, 0x5f,
	0x73, 0x72, 0x76, 0x2e, 0x64, 0x65, 0x74, 0x65, 0x63, 0x74, 0x2e, 0x47, 0x65, 0x74, 0x44, 0x65,
	0x74, 0x65, 0x63, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x60, 0x0a, 0x0a, 0x4c, 0x69, 0x73,
	0x74, 0x44, 0x65, 0x74, 0x65, 0x63, 0x74, 0x12, 0x29, 0x2e, 0x62, 0x69, 0x7a, 0x2e, 0x62, 0x69,
	0x72, 0x64, 0x5f, 0x61, 0x69, 0x5f, 0x73, 0x72, 0x76, 0x2e, 0x64, 0x65, 0x74, 0x65, 0x63, 0x74,
	0x2e, 0x4c, 0x69, 0x73, 0x74, 0x44, 0x65, 0x74, 0x65, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x27, 0x2e, 0x62, 0x69, 0x7a, 0x2e, 0x62, 0x69, 0x72, 0x64, 0x5f, 0x61, 0x69,
	0x5f, 0x73, 0x72, 0x76, 0x2e, 0x64, 0x65, 0x74, 0x65, 0x63, 0x74, 0x2e, 0x4c, 0x69, 0x73, 0x74,
	0x44, 0x65, 0x74, 0x65, 0x63, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x5f, 0x0a, 0x0b, 0x41,
	0x49, 0x44, 0x65, 0x74, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x28, 0x2e, 0x62, 0x69, 0x7a,
	0x2e, 0x62, 0x69, 0x72, 0x64, 0x5f, 0x61, 0x69, 0x5f, 0x73, 0x72, 0x76, 0x2e, 0x64, 0x65, 0x74,
	0x65, 0x63, 0x74, 0x2e, 0x44, 0x65, 0x74, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x26, 0x2e, 0x62, 0x69, 0x7a, 0x2e, 0x62, 0x69, 0x72, 0x64, 0x5f,
	0x61, 0x69, 0x5f, 0x73, 0x72, 0x76, 0x2e, 0x64, 0x65, 0x74, 0x65, 0x63, 0x74, 0x2e, 0x44, 0x65,
	0x74, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x42, 0x2a, 0x0a, 0x0a,
	0x61, 0x70, 0x69, 0x2e, 0x64, 0x65, 0x74, 0x65, 0x63, 0x74, 0x50, 0x01, 0x5a, 0x1a, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x52, 0x65, 0x70, 0x6f, 0x2f, 0x70, 0x62, 0x2f, 0x64, 0x65, 0x74, 0x65, 0x63,
	0x74, 0x3b, 0x64, 0x65, 0x74, 0x65, 0x63, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_bird_ai_bird_detect_detect_proto_rawDescOnce sync.Once
	file_bird_ai_bird_detect_detect_proto_rawDescData = file_bird_ai_bird_detect_detect_proto_rawDesc
)

func file_bird_ai_bird_detect_detect_proto_rawDescGZIP() []byte {
	file_bird_ai_bird_detect_detect_proto_rawDescOnce.Do(func() {
		file_bird_ai_bird_detect_detect_proto_rawDescData = protoimpl.X.CompressGZIP(file_bird_ai_bird_detect_detect_proto_rawDescData)
	})
	return file_bird_ai_bird_detect_detect_proto_rawDescData
}

var file_bird_ai_bird_detect_detect_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_bird_ai_bird_detect_detect_proto_goTypes = []interface{}{
	(*CreateDetectRequest)(nil), // 0: biz.bird_ai_srv.detect.CreateDetectRequest
	(*CreateDetectReply)(nil),   // 1: biz.bird_ai_srv.detect.CreateDetectReply
	(*UpdateDetectRequest)(nil), // 2: biz.bird_ai_srv.detect.UpdateDetectRequest
	(*UpdateDetectReply)(nil),   // 3: biz.bird_ai_srv.detect.UpdateDetectReply
	(*DeleteDetectRequest)(nil), // 4: biz.bird_ai_srv.detect.DeleteDetectRequest
	(*DeleteDetectReply)(nil),   // 5: biz.bird_ai_srv.detect.DeleteDetectReply
	(*GetDetectRequest)(nil),    // 6: biz.bird_ai_srv.detect.GetDetectRequest
	(*GetDetectReply)(nil),      // 7: biz.bird_ai_srv.detect.GetDetectReply
	(*ListDetectRequest)(nil),   // 8: biz.bird_ai_srv.detect.ListDetectRequest
	(*ListDetectReply)(nil),     // 9: biz.bird_ai_srv.detect.ListDetectReply
	(*DetectionRequest)(nil),    // 10: biz.bird_ai_srv.detect.DetectionRequest
	(*DetectionReply)(nil),      // 11: biz.bird_ai_srv.detect.DetectionReply
}
var file_bird_ai_bird_detect_detect_proto_depIdxs = []int32{
	0,  // 0: biz.bird_ai_srv.detect.Detect.CreateDetect:input_type -> biz.bird_ai_srv.detect.CreateDetectRequest
	2,  // 1: biz.bird_ai_srv.detect.Detect.UpdateDetect:input_type -> biz.bird_ai_srv.detect.UpdateDetectRequest
	4,  // 2: biz.bird_ai_srv.detect.Detect.DeleteDetect:input_type -> biz.bird_ai_srv.detect.DeleteDetectRequest
	6,  // 3: biz.bird_ai_srv.detect.Detect.GetDetect:input_type -> biz.bird_ai_srv.detect.GetDetectRequest
	8,  // 4: biz.bird_ai_srv.detect.Detect.ListDetect:input_type -> biz.bird_ai_srv.detect.ListDetectRequest
	10, // 5: biz.bird_ai_srv.detect.Detect.AIDetection:input_type -> biz.bird_ai_srv.detect.DetectionRequest
	1,  // 6: biz.bird_ai_srv.detect.Detect.CreateDetect:output_type -> biz.bird_ai_srv.detect.CreateDetectReply
	3,  // 7: biz.bird_ai_srv.detect.Detect.UpdateDetect:output_type -> biz.bird_ai_srv.detect.UpdateDetectReply
	5,  // 8: biz.bird_ai_srv.detect.Detect.DeleteDetect:output_type -> biz.bird_ai_srv.detect.DeleteDetectReply
	7,  // 9: biz.bird_ai_srv.detect.Detect.GetDetect:output_type -> biz.bird_ai_srv.detect.GetDetectReply
	9,  // 10: biz.bird_ai_srv.detect.Detect.ListDetect:output_type -> biz.bird_ai_srv.detect.ListDetectReply
	11, // 11: biz.bird_ai_srv.detect.Detect.AIDetection:output_type -> biz.bird_ai_srv.detect.DetectionReply
	6,  // [6:12] is the sub-list for method output_type
	0,  // [0:6] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_bird_ai_bird_detect_detect_proto_init() }
func file_bird_ai_bird_detect_detect_proto_init() {
	if File_bird_ai_bird_detect_detect_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_bird_ai_bird_detect_detect_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateDetectRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bird_ai_bird_detect_detect_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateDetectReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bird_ai_bird_detect_detect_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateDetectRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bird_ai_bird_detect_detect_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateDetectReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bird_ai_bird_detect_detect_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteDetectRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bird_ai_bird_detect_detect_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteDetectReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bird_ai_bird_detect_detect_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDetectRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bird_ai_bird_detect_detect_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDetectReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bird_ai_bird_detect_detect_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListDetectRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bird_ai_bird_detect_detect_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListDetectReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bird_ai_bird_detect_detect_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DetectionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bird_ai_bird_detect_detect_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DetectionReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_bird_ai_bird_detect_detect_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bird_ai_bird_detect_detect_proto_goTypes,
		DependencyIndexes: file_bird_ai_bird_detect_detect_proto_depIdxs,
		MessageInfos:      file_bird_ai_bird_detect_detect_proto_msgTypes,
	}.Build()
	File_bird_ai_bird_detect_detect_proto = out.File
	file_bird_ai_bird_detect_detect_proto_rawDesc = nil
	file_bird_ai_bird_detect_detect_proto_goTypes = nil
	file_bird_ai_bird_detect_detect_proto_depIdxs = nil
}
