// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.25.1
// source: bird_ai_bird/bird/bird_data.proto

package bird

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetBirdDistributionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 1: 周  2: 月 3: 年
	Period uint32 `protobuf:"varint,1,opt,name=period,proto3" json:"period,omitempty"`
}

func (x *GetBirdDistributionRequest) Reset() {
	*x = GetBirdDistributionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bird_ai_bird_bird_bird_data_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBirdDistributionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBirdDistributionRequest) ProtoMessage() {}

func (x *GetBirdDistributionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bird_ai_bird_bird_bird_data_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBirdDistributionRequest.ProtoReflect.Descriptor instead.
func (*GetBirdDistributionRequest) Descriptor() ([]byte, []int) {
	return file_bird_ai_bird_bird_bird_data_proto_rawDescGZIP(), []int{0}
}

func (x *GetBirdDistributionRequest) GetPeriod() uint32 {
	if x != nil {
		return x.Period
	}
	return 0
}

type GetBirdDistributionReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DeviceCoordinateList []*GetBirdDistributionReply_DeviceCoordinate `protobuf:"bytes,1,rep,name=DeviceCoordinateList,proto3" json:"DeviceCoordinateList,omitempty"`
}

func (x *GetBirdDistributionReply) Reset() {
	*x = GetBirdDistributionReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bird_ai_bird_bird_bird_data_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBirdDistributionReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBirdDistributionReply) ProtoMessage() {}

func (x *GetBirdDistributionReply) ProtoReflect() protoreflect.Message {
	mi := &file_bird_ai_bird_bird_bird_data_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBirdDistributionReply.ProtoReflect.Descriptor instead.
func (*GetBirdDistributionReply) Descriptor() ([]byte, []int) {
	return file_bird_ai_bird_bird_bird_data_proto_rawDescGZIP(), []int{1}
}

func (x *GetBirdDistributionReply) GetDeviceCoordinateList() []*GetBirdDistributionReply_DeviceCoordinate {
	if x != nil {
		return x.DeviceCoordinateList
	}
	return nil
}

type GetBirdTrackRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type uint32                    `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	Body *GetBirdTrackRequest_Body `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
}

func (x *GetBirdTrackRequest) Reset() {
	*x = GetBirdTrackRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bird_ai_bird_bird_bird_data_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBirdTrackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBirdTrackRequest) ProtoMessage() {}

func (x *GetBirdTrackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bird_ai_bird_bird_bird_data_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBirdTrackRequest.ProtoReflect.Descriptor instead.
func (*GetBirdTrackRequest) Descriptor() ([]byte, []int) {
	return file_bird_ai_bird_bird_bird_data_proto_rawDescGZIP(), []int{2}
}

func (x *GetBirdTrackRequest) GetType() uint32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *GetBirdTrackRequest) GetBody() *GetBirdTrackRequest_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

type GetBirdTrackReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BirdTrack *GetBirdTrackReply_BirdTrack `protobuf:"bytes,1,opt,name=birdTrack,proto3" json:"birdTrack,omitempty"`
}

func (x *GetBirdTrackReply) Reset() {
	*x = GetBirdTrackReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bird_ai_bird_bird_bird_data_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBirdTrackReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBirdTrackReply) ProtoMessage() {}

func (x *GetBirdTrackReply) ProtoReflect() protoreflect.Message {
	mi := &file_bird_ai_bird_bird_bird_data_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBirdTrackReply.ProtoReflect.Descriptor instead.
func (*GetBirdTrackReply) Descriptor() ([]byte, []int) {
	return file_bird_ai_bird_bird_bird_data_proto_rawDescGZIP(), []int{3}
}

func (x *GetBirdTrackReply) GetBirdTrack() *GetBirdTrackReply_BirdTrack {
	if x != nil {
		return x.BirdTrack
	}
	return nil
}

type ListBirdDynamicReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BirdDynamicList []*ListBirdDynamicReply_BirdDynamicList `protobuf:"bytes,1,rep,name=birdDynamicList,proto3" json:"birdDynamicList,omitempty"`
}

func (x *ListBirdDynamicReply) Reset() {
	*x = ListBirdDynamicReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bird_ai_bird_bird_bird_data_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListBirdDynamicReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBirdDynamicReply) ProtoMessage() {}

func (x *ListBirdDynamicReply) ProtoReflect() protoreflect.Message {
	mi := &file_bird_ai_bird_bird_bird_data_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBirdDynamicReply.ProtoReflect.Descriptor instead.
func (*ListBirdDynamicReply) Descriptor() ([]byte, []int) {
	return file_bird_ai_bird_bird_bird_data_proto_rawDescGZIP(), []int{4}
}

func (x *ListBirdDynamicReply) GetBirdDynamicList() []*ListBirdDynamicReply_BirdDynamicList {
	if x != nil {
		return x.BirdDynamicList
	}
	return nil
}

type GetBirdEvolutionReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BirdEvolutionSets []*GetBirdEvolutionReply_BirdEvolutionSets `protobuf:"bytes,1,rep,name=birdEvolutionSets,proto3" json:"birdEvolutionSets,omitempty"`
}

func (x *GetBirdEvolutionReply) Reset() {
	*x = GetBirdEvolutionReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bird_ai_bird_bird_bird_data_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBirdEvolutionReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBirdEvolutionReply) ProtoMessage() {}

func (x *GetBirdEvolutionReply) ProtoReflect() protoreflect.Message {
	mi := &file_bird_ai_bird_bird_bird_data_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBirdEvolutionReply.ProtoReflect.Descriptor instead.
func (*GetBirdEvolutionReply) Descriptor() ([]byte, []int) {
	return file_bird_ai_bird_bird_bird_data_proto_rawDescGZIP(), []int{5}
}

func (x *GetBirdEvolutionReply) GetBirdEvolutionSets() []*GetBirdEvolutionReply_BirdEvolutionSets {
	if x != nil {
		return x.BirdEvolutionSets
	}
	return nil
}

type GetBirdEvolutionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Period uint32 `protobuf:"varint,1,opt,name=period,proto3" json:"period,omitempty"`
}

func (x *GetBirdEvolutionRequest) Reset() {
	*x = GetBirdEvolutionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bird_ai_bird_bird_bird_data_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBirdEvolutionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBirdEvolutionRequest) ProtoMessage() {}

func (x *GetBirdEvolutionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bird_ai_bird_bird_bird_data_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBirdEvolutionRequest.ProtoReflect.Descriptor instead.
func (*GetBirdEvolutionRequest) Descriptor() ([]byte, []int) {
	return file_bird_ai_bird_bird_bird_data_proto_rawDescGZIP(), []int{6}
}

func (x *GetBirdEvolutionRequest) GetPeriod() uint32 {
	if x != nil {
		return x.Period
	}
	return 0
}

type GetBirdDistributionReply_DeviceCoordinate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DeviceLatitude  string                                                `protobuf:"bytes,1,opt,name=deviceLatitude,proto3" json:"deviceLatitude,omitempty"`
	DeviceLongitude string                                                `protobuf:"bytes,2,opt,name=deviceLongitude,proto3" json:"deviceLongitude,omitempty"`
	DeviceId        uint32                                                `protobuf:"varint,3,opt,name=deviceId,proto3" json:"deviceId,omitempty"`
	BirdInfoList    []*GetBirdDistributionReply_DeviceCoordinate_BirdInfo `protobuf:"bytes,4,rep,name=birdInfoList,proto3" json:"birdInfoList,omitempty"`
}

func (x *GetBirdDistributionReply_DeviceCoordinate) Reset() {
	*x = GetBirdDistributionReply_DeviceCoordinate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bird_ai_bird_bird_bird_data_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBirdDistributionReply_DeviceCoordinate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBirdDistributionReply_DeviceCoordinate) ProtoMessage() {}

func (x *GetBirdDistributionReply_DeviceCoordinate) ProtoReflect() protoreflect.Message {
	mi := &file_bird_ai_bird_bird_bird_data_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBirdDistributionReply_DeviceCoordinate.ProtoReflect.Descriptor instead.
func (*GetBirdDistributionReply_DeviceCoordinate) Descriptor() ([]byte, []int) {
	return file_bird_ai_bird_bird_bird_data_proto_rawDescGZIP(), []int{1, 0}
}

func (x *GetBirdDistributionReply_DeviceCoordinate) GetDeviceLatitude() string {
	if x != nil {
		return x.DeviceLatitude
	}
	return ""
}

func (x *GetBirdDistributionReply_DeviceCoordinate) GetDeviceLongitude() string {
	if x != nil {
		return x.DeviceLongitude
	}
	return ""
}

func (x *GetBirdDistributionReply_DeviceCoordinate) GetDeviceId() uint32 {
	if x != nil {
		return x.DeviceId
	}
	return 0
}

func (x *GetBirdDistributionReply_DeviceCoordinate) GetBirdInfoList() []*GetBirdDistributionReply_DeviceCoordinate_BirdInfo {
	if x != nil {
		return x.BirdInfoList
	}
	return nil
}

type GetBirdDistributionReply_DeviceCoordinate_BirdInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BirdId         uint32 `protobuf:"varint,1,opt,name=birdId,proto3" json:"birdId,omitempty"`
	BirdName       string `protobuf:"bytes,2,opt,name=birdName,proto3" json:"birdName,omitempty"`
	BirdTitlePhoto string `protobuf:"bytes,3,opt,name=birdTitlePhoto,proto3" json:"birdTitlePhoto,omitempty"`
}

func (x *GetBirdDistributionReply_DeviceCoordinate_BirdInfo) Reset() {
	*x = GetBirdDistributionReply_DeviceCoordinate_BirdInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bird_ai_bird_bird_bird_data_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBirdDistributionReply_DeviceCoordinate_BirdInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBirdDistributionReply_DeviceCoordinate_BirdInfo) ProtoMessage() {}

func (x *GetBirdDistributionReply_DeviceCoordinate_BirdInfo) ProtoReflect() protoreflect.Message {
	mi := &file_bird_ai_bird_bird_bird_data_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBirdDistributionReply_DeviceCoordinate_BirdInfo.ProtoReflect.Descriptor instead.
func (*GetBirdDistributionReply_DeviceCoordinate_BirdInfo) Descriptor() ([]byte, []int) {
	return file_bird_ai_bird_bird_bird_data_proto_rawDescGZIP(), []int{1, 0, 0}
}

func (x *GetBirdDistributionReply_DeviceCoordinate_BirdInfo) GetBirdId() uint32 {
	if x != nil {
		return x.BirdId
	}
	return 0
}

func (x *GetBirdDistributionReply_DeviceCoordinate_BirdInfo) GetBirdName() string {
	if x != nil {
		return x.BirdName
	}
	return ""
}

func (x *GetBirdDistributionReply_DeviceCoordinate_BirdInfo) GetBirdTitlePhoto() string {
	if x != nil {
		return x.BirdTitlePhoto
	}
	return ""
}

type GetBirdTrackRequest_Body struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *GetBirdTrackRequest_Body) Reset() {
	*x = GetBirdTrackRequest_Body{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bird_ai_bird_bird_bird_data_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBirdTrackRequest_Body) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBirdTrackRequest_Body) ProtoMessage() {}

func (x *GetBirdTrackRequest_Body) ProtoReflect() protoreflect.Message {
	mi := &file_bird_ai_bird_bird_bird_data_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBirdTrackRequest_Body.ProtoReflect.Descriptor instead.
func (*GetBirdTrackRequest_Body) Descriptor() ([]byte, []int) {
	return file_bird_ai_bird_bird_bird_data_proto_rawDescGZIP(), []int{2, 0}
}

func (x *GetBirdTrackRequest_Body) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type GetBirdTrackReply_BirdTrack struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Latitude  string `protobuf:"bytes,2,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude string `protobuf:"bytes,3,opt,name=longitude,proto3" json:"longitude,omitempty"`
	BirdId    uint32 `protobuf:"varint,4,opt,name=birdId,proto3" json:"birdId,omitempty"`
}

func (x *GetBirdTrackReply_BirdTrack) Reset() {
	*x = GetBirdTrackReply_BirdTrack{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bird_ai_bird_bird_bird_data_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBirdTrackReply_BirdTrack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBirdTrackReply_BirdTrack) ProtoMessage() {}

func (x *GetBirdTrackReply_BirdTrack) ProtoReflect() protoreflect.Message {
	mi := &file_bird_ai_bird_bird_bird_data_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBirdTrackReply_BirdTrack.ProtoReflect.Descriptor instead.
func (*GetBirdTrackReply_BirdTrack) Descriptor() ([]byte, []int) {
	return file_bird_ai_bird_bird_bird_data_proto_rawDescGZIP(), []int{3, 0}
}

func (x *GetBirdTrackReply_BirdTrack) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetBirdTrackReply_BirdTrack) GetLatitude() string {
	if x != nil {
		return x.Latitude
	}
	return ""
}

func (x *GetBirdTrackReply_BirdTrack) GetLongitude() string {
	if x != nil {
		return x.Longitude
	}
	return ""
}

func (x *GetBirdTrackReply_BirdTrack) GetBirdId() uint32 {
	if x != nil {
		return x.BirdId
	}
	return 0
}

type ListBirdDynamicReply_BirdDynamicList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Latitude  string `protobuf:"bytes,2,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude string `protobuf:"bytes,3,opt,name=longitude,proto3" json:"longitude,omitempty"`
	BirdId    uint32 `protobuf:"varint,4,opt,name=birdId,proto3" json:"birdId,omitempty"`
	Name      string `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	PhotoPath string `protobuf:"bytes,6,opt,name=photoPath,proto3" json:"photoPath,omitempty"`
	Blurb     string `protobuf:"bytes,7,opt,name=blurb,proto3" json:"blurb,omitempty"`
	Details   string `protobuf:"bytes,8,opt,name=details,proto3" json:"details,omitempty"`
}

func (x *ListBirdDynamicReply_BirdDynamicList) Reset() {
	*x = ListBirdDynamicReply_BirdDynamicList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bird_ai_bird_bird_bird_data_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListBirdDynamicReply_BirdDynamicList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBirdDynamicReply_BirdDynamicList) ProtoMessage() {}

func (x *ListBirdDynamicReply_BirdDynamicList) ProtoReflect() protoreflect.Message {
	mi := &file_bird_ai_bird_bird_bird_data_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBirdDynamicReply_BirdDynamicList.ProtoReflect.Descriptor instead.
func (*ListBirdDynamicReply_BirdDynamicList) Descriptor() ([]byte, []int) {
	return file_bird_ai_bird_bird_bird_data_proto_rawDescGZIP(), []int{4, 0}
}

func (x *ListBirdDynamicReply_BirdDynamicList) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ListBirdDynamicReply_BirdDynamicList) GetLatitude() string {
	if x != nil {
		return x.Latitude
	}
	return ""
}

func (x *ListBirdDynamicReply_BirdDynamicList) GetLongitude() string {
	if x != nil {
		return x.Longitude
	}
	return ""
}

func (x *ListBirdDynamicReply_BirdDynamicList) GetBirdId() uint32 {
	if x != nil {
		return x.BirdId
	}
	return 0
}

func (x *ListBirdDynamicReply_BirdDynamicList) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ListBirdDynamicReply_BirdDynamicList) GetPhotoPath() string {
	if x != nil {
		return x.PhotoPath
	}
	return ""
}

func (x *ListBirdDynamicReply_BirdDynamicList) GetBlurb() string {
	if x != nil {
		return x.Blurb
	}
	return ""
}

func (x *ListBirdDynamicReply_BirdDynamicList) GetDetails() string {
	if x != nil {
		return x.Details
	}
	return ""
}

type GetBirdEvolutionReply_BirdEvolutionSets struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BirdEvolutionList []*GetBirdEvolutionReply_BirdEvolutionSets_BirdEvolution `protobuf:"bytes,1,rep,name=birdEvolutionList,proto3" json:"birdEvolutionList,omitempty"`
	Timestamp         string                                                   `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
}

func (x *GetBirdEvolutionReply_BirdEvolutionSets) Reset() {
	*x = GetBirdEvolutionReply_BirdEvolutionSets{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bird_ai_bird_bird_bird_data_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBirdEvolutionReply_BirdEvolutionSets) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBirdEvolutionReply_BirdEvolutionSets) ProtoMessage() {}

func (x *GetBirdEvolutionReply_BirdEvolutionSets) ProtoReflect() protoreflect.Message {
	mi := &file_bird_ai_bird_bird_bird_data_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBirdEvolutionReply_BirdEvolutionSets.ProtoReflect.Descriptor instead.
func (*GetBirdEvolutionReply_BirdEvolutionSets) Descriptor() ([]byte, []int) {
	return file_bird_ai_bird_bird_bird_data_proto_rawDescGZIP(), []int{5, 0}
}

func (x *GetBirdEvolutionReply_BirdEvolutionSets) GetBirdEvolutionList() []*GetBirdEvolutionReply_BirdEvolutionSets_BirdEvolution {
	if x != nil {
		return x.BirdEvolutionList
	}
	return nil
}

func (x *GetBirdEvolutionReply_BirdEvolutionSets) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

type GetBirdEvolutionReply_BirdEvolutionSets_BirdEvolution struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Latitude  string `protobuf:"bytes,2,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude string `protobuf:"bytes,3,opt,name=longitude,proto3" json:"longitude,omitempty"`
	BirdCount uint32 `protobuf:"varint,4,opt,name=birdCount,proto3" json:"birdCount,omitempty"`
}

func (x *GetBirdEvolutionReply_BirdEvolutionSets_BirdEvolution) Reset() {
	*x = GetBirdEvolutionReply_BirdEvolutionSets_BirdEvolution{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bird_ai_bird_bird_bird_data_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBirdEvolutionReply_BirdEvolutionSets_BirdEvolution) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBirdEvolutionReply_BirdEvolutionSets_BirdEvolution) ProtoMessage() {}

func (x *GetBirdEvolutionReply_BirdEvolutionSets_BirdEvolution) ProtoReflect() protoreflect.Message {
	mi := &file_bird_ai_bird_bird_bird_data_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBirdEvolutionReply_BirdEvolutionSets_BirdEvolution.ProtoReflect.Descriptor instead.
func (*GetBirdEvolutionReply_BirdEvolutionSets_BirdEvolution) Descriptor() ([]byte, []int) {
	return file_bird_ai_bird_bird_bird_data_proto_rawDescGZIP(), []int{5, 0, 0}
}

func (x *GetBirdEvolutionReply_BirdEvolutionSets_BirdEvolution) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetBirdEvolutionReply_BirdEvolutionSets_BirdEvolution) GetLatitude() string {
	if x != nil {
		return x.Latitude
	}
	return ""
}

func (x *GetBirdEvolutionReply_BirdEvolutionSets_BirdEvolution) GetLongitude() string {
	if x != nil {
		return x.Longitude
	}
	return ""
}

func (x *GetBirdEvolutionReply_BirdEvolutionSets_BirdEvolution) GetBirdCount() uint32 {
	if x != nil {
		return x.BirdCount
	}
	return 0
}

var File_bird_ai_bird_bird_bird_data_proto protoreflect.FileDescriptor

var file_bird_ai_bird_bird_bird_data_proto_rawDesc = []byte{
	0x0a, 0x21, 0x62, 0x69, 0x72, 0x64, 0x5f, 0x61, 0x69, 0x5f, 0x62, 0x69, 0x72, 0x64, 0x2f, 0x62,
	0x69, 0x72, 0x64, 0x2f, 0x62, 0x69, 0x72, 0x64, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x14, 0x62, 0x69, 0x7a, 0x2e, 0x62, 0x69, 0x72, 0x64, 0x5f, 0x61, 0x69,
	0x5f, 0x73, 0x72, 0x76, 0x2e, 0x62, 0x69, 0x72, 0x64, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61,
	0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x34, 0x0a, 0x1a, 0x47, 0x65, 0x74, 0x42, 0x69, 0x72, 0x64, 0x44,
	0x69, 0x73, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x06, 0x70, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x22, 0xe8, 0x03, 0x0a, 0x18, 0x47,
	0x65, 0x74, 0x42, 0x69, 0x72, 0x64, 0x44, 0x69, 0x73, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x73, 0x0a, 0x14, 0x44, 0x65, 0x76, 0x69, 0x63,
	0x65, 0x43, 0x6f, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x3f, 0x2e, 0x62, 0x69, 0x7a, 0x2e, 0x62, 0x69, 0x72, 0x64,
	0x5f, 0x61, 0x69, 0x5f, 0x73, 0x72, 0x76, 0x2e, 0x62, 0x69, 0x72, 0x64, 0x2e, 0x47, 0x65, 0x74,
	0x42, 0x69, 0x72, 0x64, 0x44, 0x69, 0x73, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x2e, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x43, 0x6f, 0x6f, 0x72,
	0x64, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x52, 0x14, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x43, 0x6f,
	0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x1a, 0xd6, 0x02, 0x0a,
	0x10, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x43, 0x6f, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x74,
	0x65, 0x12, 0x26, 0x0a, 0x0e, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x4c, 0x61, 0x74, 0x69, 0x74,
	0x75, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x64, 0x65, 0x76, 0x69, 0x63,
	0x65, 0x4c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x12, 0x28, 0x0a, 0x0f, 0x64, 0x65, 0x76,
	0x69, 0x63, 0x65, 0x4c, 0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0f, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x4c, 0x6f, 0x6e, 0x67, 0x69, 0x74,
	0x75, 0x64, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x64, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x64, 0x12,
	0x6c, 0x0a, 0x0c, 0x62, 0x69, 0x72, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x4c, 0x69, 0x73, 0x74, 0x18,
	0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x48, 0x2e, 0x62, 0x69, 0x7a, 0x2e, 0x62, 0x69, 0x72, 0x64,
	0x5f, 0x61, 0x69, 0x5f, 0x73, 0x72, 0x76, 0x2e, 0x62, 0x69, 0x72, 0x64, 0x2e, 0x47, 0x65, 0x74,
	0x42, 0x69, 0x72, 0x64, 0x44, 0x69, 0x73, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x2e, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x43, 0x6f, 0x6f, 0x72,
	0x64, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x2e, 0x42, 0x69, 0x72, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x0c, 0x62, 0x69, 0x72, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x4c, 0x69, 0x73, 0x74, 0x1a, 0x66, 0x0a,
	0x08, 0x42, 0x69, 0x72, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x16, 0x0a, 0x06, 0x62, 0x69, 0x72,
	0x64, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x62, 0x69, 0x72, 0x64, 0x49,
	0x64, 0x12, 0x1a, 0x0a, 0x08, 0x62, 0x69, 0x72, 0x64, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x62, 0x69, 0x72, 0x64, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x26, 0x0a,
	0x0e, 0x62, 0x69, 0x72, 0x64, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x50, 0x68, 0x6f, 0x74, 0x6f, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x62, 0x69, 0x72, 0x64, 0x54, 0x69, 0x74, 0x6c, 0x65,
	0x50, 0x68, 0x6f, 0x74, 0x6f, 0x22, 0x87, 0x01, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x42, 0x69, 0x72,
	0x64, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x12, 0x42, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x2e, 0x2e, 0x62, 0x69, 0x7a, 0x2e, 0x62, 0x69, 0x72, 0x64, 0x5f, 0x61, 0x69, 0x5f, 0x73, 0x72,
	0x76, 0x2e, 0x62, 0x69, 0x72, 0x64, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x69, 0x72, 0x64, 0x54, 0x72,
	0x61, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x42, 0x6f, 0x64, 0x79, 0x52,
	0x04, 0x62, 0x6f, 0x64, 0x79, 0x1a, 0x18, 0x0a, 0x04, 0x42, 0x6f, 0x64, 0x79, 0x12, 0x10, 0x0a,
	0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x22,
	0xd3, 0x01, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x42, 0x69, 0x72, 0x64, 0x54, 0x72, 0x61, 0x63, 0x6b,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x4f, 0x0a, 0x09, 0x62, 0x69, 0x72, 0x64, 0x54, 0x72, 0x61,
	0x63, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x31, 0x2e, 0x62, 0x69, 0x7a, 0x2e, 0x62,
	0x69, 0x72, 0x64, 0x5f, 0x61, 0x69, 0x5f, 0x73, 0x72, 0x76, 0x2e, 0x62, 0x69, 0x72, 0x64, 0x2e,
	0x47, 0x65, 0x74, 0x42, 0x69, 0x72, 0x64, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x2e, 0x42, 0x69, 0x72, 0x64, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x52, 0x09, 0x62, 0x69, 0x72,
	0x64, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x1a, 0x6d, 0x0a, 0x09, 0x42, 0x69, 0x72, 0x64, 0x54, 0x72,
	0x61, 0x63, 0x6b, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x12,
	0x1c, 0x0a, 0x09, 0x6c, 0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x6c, 0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75, 0x64, 0x65, 0x12, 0x16, 0x0a,
	0x06, 0x62, 0x69, 0x72, 0x64, 0x49, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x62,
	0x69, 0x72, 0x64, 0x49, 0x64, 0x22, 0xd4, 0x02, 0x0a, 0x14, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x69,
	0x72, 0x64, 0x44, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x64,
	0x0a, 0x0f, 0x62, 0x69, 0x72, 0x64, 0x44, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63, 0x4c, 0x69, 0x73,
	0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x3a, 0x2e, 0x62, 0x69, 0x7a, 0x2e, 0x62, 0x69,
	0x72, 0x64, 0x5f, 0x61, 0x69, 0x5f, 0x73, 0x72, 0x76, 0x2e, 0x62, 0x69, 0x72, 0x64, 0x2e, 0x4c,
	0x69, 0x73, 0x74, 0x42, 0x69, 0x72, 0x64, 0x44, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x2e, 0x42, 0x69, 0x72, 0x64, 0x44, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63, 0x4c,
	0x69, 0x73, 0x74, 0x52, 0x0f, 0x62, 0x69, 0x72, 0x64, 0x44, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63,
	0x4c, 0x69, 0x73, 0x74, 0x1a, 0xd5, 0x01, 0x0a, 0x0f, 0x42, 0x69, 0x72, 0x64, 0x44, 0x79, 0x6e,
	0x61, 0x6d, 0x69, 0x63, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x61, 0x74, 0x69,
	0x74, 0x75, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x61, 0x74, 0x69,
	0x74, 0x75, 0x64, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x6c, 0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75, 0x64,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6c, 0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75,
	0x64, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x62, 0x69, 0x72, 0x64, 0x49, 0x64, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x06, 0x62, 0x69, 0x72, 0x64, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1c,
	0x0a, 0x09, 0x70, 0x68, 0x6f, 0x74, 0x6f, 0x50, 0x61, 0x74, 0x68, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x70, 0x68, 0x6f, 0x74, 0x6f, 0x50, 0x61, 0x74, 0x68, 0x12, 0x14, 0x0a, 0x05,
	0x62, 0x6c, 0x75, 0x72, 0x62, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x62, 0x6c, 0x75,
	0x72, 0x62, 0x12, 0x18, 0x0a, 0x07, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x18, 0x08, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x22, 0xac, 0x03, 0x0a,
	0x15, 0x47, 0x65, 0x74, 0x42, 0x69, 0x72, 0x64, 0x45, 0x76, 0x6f, 0x6c, 0x75, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x6b, 0x0a, 0x11, 0x62, 0x69, 0x72, 0x64, 0x45, 0x76,
	0x6f, 0x6c, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x3d, 0x2e, 0x62, 0x69, 0x7a, 0x2e, 0x62, 0x69, 0x72, 0x64, 0x5f, 0x61, 0x69, 0x5f,
	0x73, 0x72, 0x76, 0x2e, 0x62, 0x69, 0x72, 0x64, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x69, 0x72, 0x64,
	0x45, 0x76, 0x6f, 0x6c, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x2e, 0x42,
	0x69, 0x72, 0x64, 0x45, 0x76, 0x6f, 0x6c, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x74, 0x73,
	0x52, 0x11, 0x62, 0x69, 0x72, 0x64, 0x45, 0x76, 0x6f, 0x6c, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x53,
	0x65, 0x74, 0x73, 0x1a, 0xa5, 0x02, 0x0a, 0x11, 0x42, 0x69, 0x72, 0x64, 0x45, 0x76, 0x6f, 0x6c,
	0x75, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x74, 0x73, 0x12, 0x79, 0x0a, 0x11, 0x62, 0x69, 0x72,
	0x64, 0x45, 0x76, 0x6f, 0x6c, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x4b, 0x2e, 0x62, 0x69, 0x7a, 0x2e, 0x62, 0x69, 0x72, 0x64, 0x5f,
	0x61, 0x69, 0x5f, 0x73, 0x72, 0x76, 0x2e, 0x62, 0x69, 0x72, 0x64, 0x2e, 0x47, 0x65, 0x74, 0x42,
	0x69, 0x72, 0x64, 0x45, 0x76, 0x6f, 0x6c, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x2e, 0x42, 0x69, 0x72, 0x64, 0x45, 0x76, 0x6f, 0x6c, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x53,
	0x65, 0x74, 0x73, 0x2e, 0x42, 0x69, 0x72, 0x64, 0x45, 0x76, 0x6f, 0x6c, 0x75, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x11, 0x62, 0x69, 0x72, 0x64, 0x45, 0x76, 0x6f, 0x6c, 0x75, 0x74, 0x69, 0x6f, 0x6e,
	0x4c, 0x69, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x1a, 0x77, 0x0a, 0x0d, 0x42, 0x69, 0x72, 0x64, 0x45, 0x76, 0x6f, 0x6c, 0x75, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x12,
	0x1c, 0x0a, 0x09, 0x6c, 0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x6c, 0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75, 0x64, 0x65, 0x12, 0x1c, 0x0a,
	0x09, 0x62, 0x69, 0x72, 0x64, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x09, 0x62, 0x69, 0x72, 0x64, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x31, 0x0a, 0x17, 0x47,
	0x65, 0x74, 0x42, 0x69, 0x72, 0x64, 0x45, 0x76, 0x6f, 0x6c, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x65, 0x72, 0x69, 0x6f, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x70, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x32, 0x9a,
	0x04, 0x0a, 0x08, 0x42, 0x69, 0x72, 0x64, 0x44, 0x61, 0x74, 0x61, 0x12, 0x76, 0x0a, 0x0f, 0x4c,
	0x69, 0x73, 0x74, 0x42, 0x69, 0x72, 0x64, 0x44, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63, 0x12, 0x16,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x2a, 0x2e, 0x62, 0x69, 0x7a, 0x2e, 0x62, 0x69, 0x72,
	0x64, 0x5f, 0x61, 0x69, 0x5f, 0x73, 0x72, 0x76, 0x2e, 0x62, 0x69, 0x72, 0x64, 0x2e, 0x4c, 0x69,
	0x73, 0x74, 0x42, 0x69, 0x72, 0x64, 0x44, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x22, 0x1f, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x19, 0x12, 0x17, 0x79, 0x77, 0x2f, 0x62,
	0x69, 0x72, 0x64, 0x2f, 0x6c, 0x69, 0x73, 0x74, 0x42, 0x69, 0x72, 0x64, 0x44, 0x79, 0x6e, 0x61,
	0x6d, 0x69, 0x63, 0x12, 0x64, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x42, 0x69, 0x72, 0x64, 0x54, 0x72,
	0x61, 0x63, 0x6b, 0x12, 0x29, 0x2e, 0x62, 0x69, 0x7a, 0x2e, 0x62, 0x69, 0x72, 0x64, 0x5f, 0x61,
	0x69, 0x5f, 0x73, 0x72, 0x76, 0x2e, 0x62, 0x69, 0x72, 0x64, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x69,
	0x72, 0x64, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x27,
	0x2e, 0x62, 0x69, 0x7a, 0x2e, 0x62, 0x69, 0x72, 0x64, 0x5f, 0x61, 0x69, 0x5f, 0x73, 0x72, 0x76,
	0x2e, 0x62, 0x69, 0x72, 0x64, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x69, 0x72, 0x64, 0x54, 0x72, 0x61,
	0x63, 0x6b, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x30, 0x01, 0x12, 0x90, 0x01, 0x0a, 0x10, 0x47, 0x65,
	0x74, 0x42, 0x69, 0x72, 0x64, 0x45, 0x76, 0x6f, 0x6c, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x2d,
	0x2e, 0x62, 0x69, 0x7a, 0x2e, 0x62, 0x69, 0x72, 0x64, 0x5f, 0x61, 0x69, 0x5f, 0x73, 0x72, 0x76,
	0x2e, 0x62, 0x69, 0x72, 0x64, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x69, 0x72, 0x64, 0x45, 0x76, 0x6f,
	0x6c, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2b, 0x2e,
	0x62, 0x69, 0x7a, 0x2e, 0x62, 0x69, 0x72, 0x64, 0x5f, 0x61, 0x69, 0x5f, 0x73, 0x72, 0x76, 0x2e,
	0x62, 0x69, 0x72, 0x64, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x69, 0x72, 0x64, 0x45, 0x76, 0x6f, 0x6c,
	0x75, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x20, 0x82, 0xd3, 0xe4, 0x93,
	0x02, 0x1a, 0x12, 0x18, 0x79, 0x77, 0x2f, 0x62, 0x69, 0x72, 0x64, 0x2f, 0x67, 0x65, 0x74, 0x42,
	0x69, 0x72, 0x64, 0x45, 0x76, 0x6f, 0x6c, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x9c, 0x01, 0x0a,
	0x13, 0x47, 0x65, 0x74, 0x42, 0x69, 0x72, 0x64, 0x44, 0x69, 0x73, 0x74, 0x72, 0x69, 0x62, 0x75,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x30, 0x2e, 0x62, 0x69, 0x7a, 0x2e, 0x62, 0x69, 0x72, 0x64, 0x5f,
	0x61, 0x69, 0x5f, 0x73, 0x72, 0x76, 0x2e, 0x62, 0x69, 0x72, 0x64, 0x2e, 0x47, 0x65, 0x74, 0x42,
	0x69, 0x72, 0x64, 0x44, 0x69, 0x73, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2e, 0x2e, 0x62, 0x69, 0x7a, 0x2e, 0x62, 0x69, 0x72,
	0x64, 0x5f, 0x61, 0x69, 0x5f, 0x73, 0x72, 0x76, 0x2e, 0x62, 0x69, 0x72, 0x64, 0x2e, 0x47, 0x65,
	0x74, 0x42, 0x69, 0x72, 0x64, 0x44, 0x69, 0x73, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x23, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x1d, 0x12, 0x1b,
	0x79, 0x77, 0x2f, 0x62, 0x69, 0x72, 0x64, 0x2f, 0x67, 0x65, 0x74, 0x42, 0x69, 0x72, 0x64, 0x44,
	0x69, 0x73, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x42, 0x25, 0x5a, 0x23, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x52, 0x65, 0x70, 0x6f, 0x2f, 0x70, 0x62, 0x2f, 0x62, 0x69, 0x72, 0x64,
	0x5f, 0x61, 0x69, 0x5f, 0x62, 0x69, 0x72, 0x64, 0x2f, 0x62, 0x69, 0x72, 0x64, 0x3b, 0x62, 0x69,
	0x72, 0x64, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_bird_ai_bird_bird_bird_data_proto_rawDescOnce sync.Once
	file_bird_ai_bird_bird_bird_data_proto_rawDescData = file_bird_ai_bird_bird_bird_data_proto_rawDesc
)

func file_bird_ai_bird_bird_bird_data_proto_rawDescGZIP() []byte {
	file_bird_ai_bird_bird_bird_data_proto_rawDescOnce.Do(func() {
		file_bird_ai_bird_bird_bird_data_proto_rawDescData = protoimpl.X.CompressGZIP(file_bird_ai_bird_bird_bird_data_proto_rawDescData)
	})
	return file_bird_ai_bird_bird_bird_data_proto_rawDescData
}

var file_bird_ai_bird_bird_bird_data_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_bird_ai_bird_bird_bird_data_proto_goTypes = []interface{}{
	(*GetBirdDistributionRequest)(nil),                            // 0: biz.bird_ai_srv.bird.GetBirdDistributionRequest
	(*GetBirdDistributionReply)(nil),                              // 1: biz.bird_ai_srv.bird.GetBirdDistributionReply
	(*GetBirdTrackRequest)(nil),                                   // 2: biz.bird_ai_srv.bird.GetBirdTrackRequest
	(*GetBirdTrackReply)(nil),                                     // 3: biz.bird_ai_srv.bird.GetBirdTrackReply
	(*ListBirdDynamicReply)(nil),                                  // 4: biz.bird_ai_srv.bird.ListBirdDynamicReply
	(*GetBirdEvolutionReply)(nil),                                 // 5: biz.bird_ai_srv.bird.GetBirdEvolutionReply
	(*GetBirdEvolutionRequest)(nil),                               // 6: biz.bird_ai_srv.bird.GetBirdEvolutionRequest
	(*GetBirdDistributionReply_DeviceCoordinate)(nil),             // 7: biz.bird_ai_srv.bird.GetBirdDistributionReply.DeviceCoordinate
	(*GetBirdDistributionReply_DeviceCoordinate_BirdInfo)(nil),    // 8: biz.bird_ai_srv.bird.GetBirdDistributionReply.DeviceCoordinate.BirdInfo
	(*GetBirdTrackRequest_Body)(nil),                              // 9: biz.bird_ai_srv.bird.GetBirdTrackRequest.Body
	(*GetBirdTrackReply_BirdTrack)(nil),                           // 10: biz.bird_ai_srv.bird.GetBirdTrackReply.BirdTrack
	(*ListBirdDynamicReply_BirdDynamicList)(nil),                  // 11: biz.bird_ai_srv.bird.ListBirdDynamicReply.BirdDynamicList
	(*GetBirdEvolutionReply_BirdEvolutionSets)(nil),               // 12: biz.bird_ai_srv.bird.GetBirdEvolutionReply.BirdEvolutionSets
	(*GetBirdEvolutionReply_BirdEvolutionSets_BirdEvolution)(nil), // 13: biz.bird_ai_srv.bird.GetBirdEvolutionReply.BirdEvolutionSets.BirdEvolution
	(*emptypb.Empty)(nil),                                         // 14: google.protobuf.Empty
}
var file_bird_ai_bird_bird_bird_data_proto_depIdxs = []int32{
	7,  // 0: biz.bird_ai_srv.bird.GetBirdDistributionReply.DeviceCoordinateList:type_name -> biz.bird_ai_srv.bird.GetBirdDistributionReply.DeviceCoordinate
	9,  // 1: biz.bird_ai_srv.bird.GetBirdTrackRequest.body:type_name -> biz.bird_ai_srv.bird.GetBirdTrackRequest.Body
	10, // 2: biz.bird_ai_srv.bird.GetBirdTrackReply.birdTrack:type_name -> biz.bird_ai_srv.bird.GetBirdTrackReply.BirdTrack
	11, // 3: biz.bird_ai_srv.bird.ListBirdDynamicReply.birdDynamicList:type_name -> biz.bird_ai_srv.bird.ListBirdDynamicReply.BirdDynamicList
	12, // 4: biz.bird_ai_srv.bird.GetBirdEvolutionReply.birdEvolutionSets:type_name -> biz.bird_ai_srv.bird.GetBirdEvolutionReply.BirdEvolutionSets
	8,  // 5: biz.bird_ai_srv.bird.GetBirdDistributionReply.DeviceCoordinate.birdInfoList:type_name -> biz.bird_ai_srv.bird.GetBirdDistributionReply.DeviceCoordinate.BirdInfo
	13, // 6: biz.bird_ai_srv.bird.GetBirdEvolutionReply.BirdEvolutionSets.birdEvolutionList:type_name -> biz.bird_ai_srv.bird.GetBirdEvolutionReply.BirdEvolutionSets.BirdEvolution
	14, // 7: biz.bird_ai_srv.bird.BirdData.ListBirdDynamic:input_type -> google.protobuf.Empty
	2,  // 8: biz.bird_ai_srv.bird.BirdData.GetBirdTrack:input_type -> biz.bird_ai_srv.bird.GetBirdTrackRequest
	6,  // 9: biz.bird_ai_srv.bird.BirdData.GetBirdEvolution:input_type -> biz.bird_ai_srv.bird.GetBirdEvolutionRequest
	0,  // 10: biz.bird_ai_srv.bird.BirdData.GetBirdDistribution:input_type -> biz.bird_ai_srv.bird.GetBirdDistributionRequest
	4,  // 11: biz.bird_ai_srv.bird.BirdData.ListBirdDynamic:output_type -> biz.bird_ai_srv.bird.ListBirdDynamicReply
	3,  // 12: biz.bird_ai_srv.bird.BirdData.GetBirdTrack:output_type -> biz.bird_ai_srv.bird.GetBirdTrackReply
	5,  // 13: biz.bird_ai_srv.bird.BirdData.GetBirdEvolution:output_type -> biz.bird_ai_srv.bird.GetBirdEvolutionReply
	1,  // 14: biz.bird_ai_srv.bird.BirdData.GetBirdDistribution:output_type -> biz.bird_ai_srv.bird.GetBirdDistributionReply
	11, // [11:15] is the sub-list for method output_type
	7,  // [7:11] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_bird_ai_bird_bird_bird_data_proto_init() }
func file_bird_ai_bird_bird_bird_data_proto_init() {
	if File_bird_ai_bird_bird_bird_data_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_bird_ai_bird_bird_bird_data_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBirdDistributionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bird_ai_bird_bird_bird_data_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBirdDistributionReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bird_ai_bird_bird_bird_data_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBirdTrackRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bird_ai_bird_bird_bird_data_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBirdTrackReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bird_ai_bird_bird_bird_data_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListBirdDynamicReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bird_ai_bird_bird_bird_data_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBirdEvolutionReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bird_ai_bird_bird_bird_data_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBirdEvolutionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bird_ai_bird_bird_bird_data_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBirdDistributionReply_DeviceCoordinate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bird_ai_bird_bird_bird_data_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBirdDistributionReply_DeviceCoordinate_BirdInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bird_ai_bird_bird_bird_data_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBirdTrackRequest_Body); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bird_ai_bird_bird_bird_data_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBirdTrackReply_BirdTrack); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bird_ai_bird_bird_bird_data_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListBirdDynamicReply_BirdDynamicList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bird_ai_bird_bird_bird_data_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBirdEvolutionReply_BirdEvolutionSets); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bird_ai_bird_bird_bird_data_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBirdEvolutionReply_BirdEvolutionSets_BirdEvolution); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_bird_ai_bird_bird_bird_data_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bird_ai_bird_bird_bird_data_proto_goTypes,
		DependencyIndexes: file_bird_ai_bird_bird_bird_data_proto_depIdxs,
		MessageInfos:      file_bird_ai_bird_bird_bird_data_proto_msgTypes,
	}.Build()
	File_bird_ai_bird_bird_bird_data_proto = out.File
	file_bird_ai_bird_bird_bird_data_proto_rawDesc = nil
	file_bird_ai_bird_bird_bird_data_proto_goTypes = nil
	file_bird_ai_bird_bird_bird_data_proto_depIdxs = nil
}
