// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.25.1
// source: bird_ai_srv/bird/bird_Info.proto

package bird

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/descriptorpb"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	page "proto_repo/pb/common/page"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetBirdDetailByIdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetBirdDetailByIdRequest) Reset() {
	*x = GetBirdDetailByIdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bird_ai_srv_bird_bird_Info_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBirdDetailByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBirdDetailByIdRequest) ProtoMessage() {}

func (x *GetBirdDetailByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bird_ai_srv_bird_bird_Info_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBirdDetailByIdRequest.ProtoReflect.Descriptor instead.
func (*GetBirdDetailByIdRequest) Descriptor() ([]byte, []int) {
	return file_bird_ai_srv_bird_bird_Info_proto_rawDescGZIP(), []int{0}
}

func (x *GetBirdDetailByIdRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetBirdDetailByIdReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id              int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name            string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Blurb           string `protobuf:"bytes,3,opt,name=blurb,proto3" json:"blurb,omitempty"`
	Details         string `protobuf:"bytes,4,opt,name=details,proto3" json:"details,omitempty"`
	Habitat         string `protobuf:"bytes,5,opt,name=habitat,proto3" json:"habitat,omitempty"`
	Distribution    string `protobuf:"bytes,6,opt,name=distribution,proto3" json:"distribution,omitempty"`
	Order           int32  `protobuf:"varint,10,opt,name=order,proto3" json:"order,omitempty"`
	Family          int32  `protobuf:"varint,11,opt,name=family,proto3" json:"family,omitempty"`
	Genus           int32  `protobuf:"varint,12,opt,name=genus,proto3" json:"genus,omitempty"`
	Species         int32  `protobuf:"varint,13,opt,name=species,proto3" json:"species,omitempty"`
	ProtectionGrade int32  `protobuf:"varint,14,opt,name=protectionGrade,proto3" json:"protectionGrade,omitempty"`
	EndangeredGrade int32  `protobuf:"varint,15,opt,name=endangeredGrade,proto3" json:"endangeredGrade,omitempty"`
	Resident        int32  `protobuf:"varint,16,opt,name=resident,proto3" json:"resident,omitempty"`
	Volume          int32  `protobuf:"varint,17,opt,name=volume,proto3" json:"volume,omitempty"`
	TitlePhoto      string `protobuf:"bytes,18,opt,name=titlePhoto,proto3" json:"titlePhoto,omitempty"`
}

func (x *GetBirdDetailByIdReply) Reset() {
	*x = GetBirdDetailByIdReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bird_ai_srv_bird_bird_Info_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBirdDetailByIdReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBirdDetailByIdReply) ProtoMessage() {}

func (x *GetBirdDetailByIdReply) ProtoReflect() protoreflect.Message {
	mi := &file_bird_ai_srv_bird_bird_Info_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBirdDetailByIdReply.ProtoReflect.Descriptor instead.
func (*GetBirdDetailByIdReply) Descriptor() ([]byte, []int) {
	return file_bird_ai_srv_bird_bird_Info_proto_rawDescGZIP(), []int{1}
}

func (x *GetBirdDetailByIdReply) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetBirdDetailByIdReply) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetBirdDetailByIdReply) GetBlurb() string {
	if x != nil {
		return x.Blurb
	}
	return ""
}

func (x *GetBirdDetailByIdReply) GetDetails() string {
	if x != nil {
		return x.Details
	}
	return ""
}

func (x *GetBirdDetailByIdReply) GetHabitat() string {
	if x != nil {
		return x.Habitat
	}
	return ""
}

func (x *GetBirdDetailByIdReply) GetDistribution() string {
	if x != nil {
		return x.Distribution
	}
	return ""
}

func (x *GetBirdDetailByIdReply) GetOrder() int32 {
	if x != nil {
		return x.Order
	}
	return 0
}

func (x *GetBirdDetailByIdReply) GetFamily() int32 {
	if x != nil {
		return x.Family
	}
	return 0
}

func (x *GetBirdDetailByIdReply) GetGenus() int32 {
	if x != nil {
		return x.Genus
	}
	return 0
}

func (x *GetBirdDetailByIdReply) GetSpecies() int32 {
	if x != nil {
		return x.Species
	}
	return 0
}

func (x *GetBirdDetailByIdReply) GetProtectionGrade() int32 {
	if x != nil {
		return x.ProtectionGrade
	}
	return 0
}

func (x *GetBirdDetailByIdReply) GetEndangeredGrade() int32 {
	if x != nil {
		return x.EndangeredGrade
	}
	return 0
}

func (x *GetBirdDetailByIdReply) GetResident() int32 {
	if x != nil {
		return x.Resident
	}
	return 0
}

func (x *GetBirdDetailByIdReply) GetVolume() int32 {
	if x != nil {
		return x.Volume
	}
	return 0
}

func (x *GetBirdDetailByIdReply) GetTitlePhoto() string {
	if x != nil {
		return x.TitlePhoto
	}
	return ""
}

type CreateBirdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateBirdRequest) Reset() {
	*x = CreateBirdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bird_ai_srv_bird_bird_Info_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateBirdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBirdRequest) ProtoMessage() {}

func (x *CreateBirdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bird_ai_srv_bird_bird_Info_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBirdRequest.ProtoReflect.Descriptor instead.
func (*CreateBirdRequest) Descriptor() ([]byte, []int) {
	return file_bird_ai_srv_bird_bird_Info_proto_rawDescGZIP(), []int{2}
}

type CreateBirdReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateBirdReply) Reset() {
	*x = CreateBirdReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bird_ai_srv_bird_bird_Info_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateBirdReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBirdReply) ProtoMessage() {}

func (x *CreateBirdReply) ProtoReflect() protoreflect.Message {
	mi := &file_bird_ai_srv_bird_bird_Info_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBirdReply.ProtoReflect.Descriptor instead.
func (*CreateBirdReply) Descriptor() ([]byte, []int) {
	return file_bird_ai_srv_bird_bird_Info_proto_rawDescGZIP(), []int{3}
}

type UpdateBirdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateBirdRequest) Reset() {
	*x = UpdateBirdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bird_ai_srv_bird_bird_Info_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateBirdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBirdRequest) ProtoMessage() {}

func (x *UpdateBirdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bird_ai_srv_bird_bird_Info_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBirdRequest.ProtoReflect.Descriptor instead.
func (*UpdateBirdRequest) Descriptor() ([]byte, []int) {
	return file_bird_ai_srv_bird_bird_Info_proto_rawDescGZIP(), []int{4}
}

type UpdateBirdReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateBirdReply) Reset() {
	*x = UpdateBirdReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bird_ai_srv_bird_bird_Info_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateBirdReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBirdReply) ProtoMessage() {}

func (x *UpdateBirdReply) ProtoReflect() protoreflect.Message {
	mi := &file_bird_ai_srv_bird_bird_Info_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBirdReply.ProtoReflect.Descriptor instead.
func (*UpdateBirdReply) Descriptor() ([]byte, []int) {
	return file_bird_ai_srv_bird_bird_Info_proto_rawDescGZIP(), []int{5}
}

type DeleteBirdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteBirdRequest) Reset() {
	*x = DeleteBirdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bird_ai_srv_bird_bird_Info_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteBirdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBirdRequest) ProtoMessage() {}

func (x *DeleteBirdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bird_ai_srv_bird_bird_Info_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBirdRequest.ProtoReflect.Descriptor instead.
func (*DeleteBirdRequest) Descriptor() ([]byte, []int) {
	return file_bird_ai_srv_bird_bird_Info_proto_rawDescGZIP(), []int{6}
}

type DeleteBirdReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteBirdReply) Reset() {
	*x = DeleteBirdReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bird_ai_srv_bird_bird_Info_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteBirdReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBirdReply) ProtoMessage() {}

func (x *DeleteBirdReply) ProtoReflect() protoreflect.Message {
	mi := &file_bird_ai_srv_bird_bird_Info_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBirdReply.ProtoReflect.Descriptor instead.
func (*DeleteBirdReply) Descriptor() ([]byte, []int) {
	return file_bird_ai_srv_bird_bird_Info_proto_rawDescGZIP(), []int{7}
}

type GetBirdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetBirdRequest) Reset() {
	*x = GetBirdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bird_ai_srv_bird_bird_Info_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBirdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBirdRequest) ProtoMessage() {}

func (x *GetBirdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bird_ai_srv_bird_bird_Info_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBirdRequest.ProtoReflect.Descriptor instead.
func (*GetBirdRequest) Descriptor() ([]byte, []int) {
	return file_bird_ai_srv_bird_bird_Info_proto_rawDescGZIP(), []int{8}
}

type GetBirdReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetBirdReply) Reset() {
	*x = GetBirdReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bird_ai_srv_bird_bird_Info_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBirdReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBirdReply) ProtoMessage() {}

func (x *GetBirdReply) ProtoReflect() protoreflect.Message {
	mi := &file_bird_ai_srv_bird_bird_Info_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBirdReply.ProtoReflect.Descriptor instead.
func (*GetBirdReply) Descriptor() ([]byte, []int) {
	return file_bird_ai_srv_bird_bird_Info_proto_rawDescGZIP(), []int{9}
}

type ListBirdOrderReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BirdOrderList []*ListBirdOrderReply_BirdOrderList `protobuf:"bytes,1,rep,name=birdOrderList,proto3" json:"birdOrderList,omitempty"`
}

func (x *ListBirdOrderReply) Reset() {
	*x = ListBirdOrderReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bird_ai_srv_bird_bird_Info_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListBirdOrderReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBirdOrderReply) ProtoMessage() {}

func (x *ListBirdOrderReply) ProtoReflect() protoreflect.Message {
	mi := &file_bird_ai_srv_bird_bird_Info_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBirdOrderReply.ProtoReflect.Descriptor instead.
func (*ListBirdOrderReply) Descriptor() ([]byte, []int) {
	return file_bird_ai_srv_bird_bird_Info_proto_rawDescGZIP(), []int{10}
}

func (x *ListBirdOrderReply) GetBirdOrderList() []*ListBirdOrderReply_BirdOrderList {
	if x != nil {
		return x.BirdOrderList
	}
	return nil
}

type ListBirdBaseByOrderRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Order uint32          `protobuf:"varint,1,opt,name=order,proto3" json:"order,omitempty"`
	Page  *page.PageQuery `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
}

func (x *ListBirdBaseByOrderRequest) Reset() {
	*x = ListBirdBaseByOrderRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bird_ai_srv_bird_bird_Info_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListBirdBaseByOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBirdBaseByOrderRequest) ProtoMessage() {}

func (x *ListBirdBaseByOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bird_ai_srv_bird_bird_Info_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBirdBaseByOrderRequest.ProtoReflect.Descriptor instead.
func (*ListBirdBaseByOrderRequest) Descriptor() ([]byte, []int) {
	return file_bird_ai_srv_bird_bird_Info_proto_rawDescGZIP(), []int{11}
}

func (x *ListBirdBaseByOrderRequest) GetOrder() uint32 {
	if x != nil {
		return x.Order
	}
	return 0
}

func (x *ListBirdBaseByOrderRequest) GetPage() *page.PageQuery {
	if x != nil {
		return x.Page
	}
	return nil
}

type BirdBase struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name       string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	TitlePhoto string `protobuf:"bytes,4,opt,name=titlePhoto,proto3" json:"titlePhoto,omitempty"`
}

func (x *BirdBase) Reset() {
	*x = BirdBase{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bird_ai_srv_bird_bird_Info_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BirdBase) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BirdBase) ProtoMessage() {}

func (x *BirdBase) ProtoReflect() protoreflect.Message {
	mi := &file_bird_ai_srv_bird_bird_Info_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BirdBase.ProtoReflect.Descriptor instead.
func (*BirdBase) Descriptor() ([]byte, []int) {
	return file_bird_ai_srv_bird_bird_Info_proto_rawDescGZIP(), []int{12}
}

func (x *BirdBase) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *BirdBase) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BirdBase) GetTitlePhoto() string {
	if x != nil {
		return x.TitlePhoto
	}
	return ""
}

type ListBirdBaseByOrderReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PageInfo *page.PageInfo `protobuf:"bytes,1,opt,name=page_info,json=pageInfo,proto3" json:"page_info,omitempty"`
	List     []*BirdBase    `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
}

func (x *ListBirdBaseByOrderReply) Reset() {
	*x = ListBirdBaseByOrderReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bird_ai_srv_bird_bird_Info_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListBirdBaseByOrderReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBirdBaseByOrderReply) ProtoMessage() {}

func (x *ListBirdBaseByOrderReply) ProtoReflect() protoreflect.Message {
	mi := &file_bird_ai_srv_bird_bird_Info_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBirdBaseByOrderReply.ProtoReflect.Descriptor instead.
func (*ListBirdBaseByOrderReply) Descriptor() ([]byte, []int) {
	return file_bird_ai_srv_bird_bird_Info_proto_rawDescGZIP(), []int{13}
}

func (x *ListBirdBaseByOrderReply) GetPageInfo() *page.PageInfo {
	if x != nil {
		return x.PageInfo
	}
	return nil
}

func (x *ListBirdBaseByOrderReply) GetList() []*BirdBase {
	if x != nil {
		return x.List
	}
	return nil
}

type ListBirdOrderReply_BirdOrderList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *ListBirdOrderReply_BirdOrderList) Reset() {
	*x = ListBirdOrderReply_BirdOrderList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bird_ai_srv_bird_bird_Info_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListBirdOrderReply_BirdOrderList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBirdOrderReply_BirdOrderList) ProtoMessage() {}

func (x *ListBirdOrderReply_BirdOrderList) ProtoReflect() protoreflect.Message {
	mi := &file_bird_ai_srv_bird_bird_Info_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBirdOrderReply_BirdOrderList.ProtoReflect.Descriptor instead.
func (*ListBirdOrderReply_BirdOrderList) Descriptor() ([]byte, []int) {
	return file_bird_ai_srv_bird_bird_Info_proto_rawDescGZIP(), []int{10, 0}
}

func (x *ListBirdOrderReply_BirdOrderList) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ListBirdOrderReply_BirdOrderList) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_bird_ai_srv_bird_bird_Info_proto protoreflect.FileDescriptor

var file_bird_ai_srv_bird_bird_Info_proto_rawDesc = []byte{
	0x0a, 0x20, 0x62, 0x69, 0x72, 0x64, 0x5f, 0x61, 0x69, 0x5f, 0x73, 0x72, 0x76, 0x2f, 0x62, 0x69,
	0x72, 0x64, 0x2f, 0x62, 0x69, 0x72, 0x64, 0x5f, 0x49, 0x6e, 0x66, 0x6f, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x14, 0x62, 0x69, 0x7a, 0x2e, 0x62, 0x69, 0x72, 0x64, 0x5f, 0x61, 0x69, 0x5f,
	0x73, 0x72, 0x76, 0x2e, 0x62, 0x69, 0x72, 0x64, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x1a, 0x16, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x70, 0x61, 0x67, 0x65,
	0x2f, 0x70, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x20, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x64, 0x65, 0x73,
	0x63, 0x72, 0x69, 0x70, 0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x2a, 0x0a,
	0x18, 0x47, 0x65, 0x74, 0x42, 0x69, 0x72, 0x64, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x42, 0x79,
	0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x22, 0xb0, 0x03, 0x0a, 0x16, 0x47, 0x65,
	0x74, 0x42, 0x69, 0x72, 0x64, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x42, 0x79, 0x49, 0x64, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x62, 0x6c, 0x75, 0x72,
	0x62, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x62, 0x6c, 0x75, 0x72, 0x62, 0x12, 0x18,
	0x0a, 0x07, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x68, 0x61, 0x62, 0x69,
	0x74, 0x61, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x68, 0x61, 0x62, 0x69, 0x74,
	0x61, 0x74, 0x12, 0x22, 0x0a, 0x0c, 0x64, 0x69, 0x73, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x64, 0x69, 0x73, 0x74, 0x72, 0x69,
	0x62, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x18,
	0x0a, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06,
	0x66, 0x61, 0x6d, 0x69, 0x6c, 0x79, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x66, 0x61,
	0x6d, 0x69, 0x6c, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x67, 0x65, 0x6e, 0x75, 0x73, 0x18, 0x0c, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x05, 0x67, 0x65, 0x6e, 0x75, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x70,
	0x65, 0x63, 0x69, 0x65, 0x73, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x73, 0x70, 0x65,
	0x63, 0x69, 0x65, 0x73, 0x12, 0x28, 0x0a, 0x0f, 0x70, 0x72, 0x6f, 0x74, 0x65, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x47, 0x72, 0x61, 0x64, 0x65, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0f, 0x70,
	0x72, 0x6f, 0x74, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x47, 0x72, 0x61, 0x64, 0x65, 0x12, 0x28,
	0x0a, 0x0f, 0x65, 0x6e, 0x64, 0x61, 0x6e, 0x67, 0x65, 0x72, 0x65, 0x64, 0x47, 0x72, 0x61, 0x64,
	0x65, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0f, 0x65, 0x6e, 0x64, 0x61, 0x6e, 0x67, 0x65,
	0x72, 0x65, 0x64, 0x47, 0x72, 0x61, 0x64, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x69,
	0x64, 0x65, 0x6e, 0x74, 0x18, 0x10, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x72, 0x65, 0x73, 0x69,
	0x64, 0x65, 0x6e, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x76, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x18, 0x11,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x76, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x0a,
	0x74, 0x69, 0x74, 0x6c, 0x65, 0x50, 0x68, 0x6f, 0x74, 0x6f, 0x18, 0x12, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x50, 0x68, 0x6f, 0x74, 0x6f, 0x22, 0x13, 0x0a, 0x11,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x69, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x22, 0x11, 0x0a, 0x0f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x69, 0x72, 0x64, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x22, 0x13, 0x0a, 0x11, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x42, 0x69,
	0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x11, 0x0a, 0x0f, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x42, 0x69, 0x72, 0x64, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x13, 0x0a, 0x11,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x69, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x22, 0x11, 0x0a, 0x0f, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x69, 0x72, 0x64, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x22, 0x10, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x42, 0x69, 0x72, 0x64, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x0e, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x42, 0x69, 0x72,
	0x64, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0xa7, 0x01, 0x0a, 0x12, 0x4c, 0x69, 0x73, 0x74, 0x42,
	0x69, 0x72, 0x64, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x5c, 0x0a,
	0x0d, 0x62, 0x69, 0x72, 0x64, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x36, 0x2e, 0x62, 0x69, 0x7a, 0x2e, 0x62, 0x69, 0x72, 0x64, 0x5f,
	0x61, 0x69, 0x5f, 0x73, 0x72, 0x76, 0x2e, 0x62, 0x69, 0x72, 0x64, 0x2e, 0x4c, 0x69, 0x73, 0x74,
	0x42, 0x69, 0x72, 0x64, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x2e, 0x42,
	0x69, 0x72, 0x64, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x0d, 0x62, 0x69,
	0x72, 0x64, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x1a, 0x33, 0x0a, 0x0d, 0x42,
	0x69, 0x72, 0x64, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x22, 0x57, 0x0a, 0x1a, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x69, 0x72, 0x64, 0x42, 0x61, 0x73, 0x65,
	0x42, 0x79, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14,
	0x0a, 0x05, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x6f,
	0x72, 0x64, 0x65, 0x72, 0x12, 0x23, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x61, 0x67, 0x65, 0x2e, 0x50, 0x61, 0x67, 0x65, 0x51, 0x75,
	0x65, 0x72, 0x79, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x22, 0x4e, 0x0a, 0x08, 0x42, 0x69, 0x72,
	0x64, 0x42, 0x61, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x74, 0x69, 0x74,
	0x6c, 0x65, 0x50, 0x68, 0x6f, 0x74, 0x6f, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x74,
	0x69, 0x74, 0x6c, 0x65, 0x50, 0x68, 0x6f, 0x74, 0x6f, 0x22, 0x7b, 0x0a, 0x18, 0x4c, 0x69, 0x73,
	0x74, 0x42, 0x69, 0x72, 0x64, 0x42, 0x61, 0x73, 0x65, 0x42, 0x79, 0x4f, 0x72, 0x64, 0x65, 0x72,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x2b, 0x0a, 0x09, 0x70, 0x61, 0x67, 0x65, 0x5f, 0x69, 0x6e,
	0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x61, 0x67, 0x65, 0x2e,
	0x50, 0x61, 0x67, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x08, 0x70, 0x61, 0x67, 0x65, 0x49, 0x6e,
	0x66, 0x6f, 0x12, 0x32, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x1e, 0x2e, 0x62, 0x69, 0x7a, 0x2e, 0x62, 0x69, 0x72, 0x64, 0x5f, 0x61, 0x69, 0x5f, 0x73,
	0x72, 0x76, 0x2e, 0x62, 0x69, 0x72, 0x64, 0x2e, 0x42, 0x69, 0x72, 0x64, 0x42, 0x61, 0x73, 0x65,
	0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x32, 0x99, 0x06, 0x0a, 0x08, 0x42, 0x69, 0x72, 0x64, 0x49,
	0x6e, 0x66, 0x6f, 0x12, 0x5c, 0x0a, 0x0a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x69, 0x72,
	0x64, 0x12, 0x27, 0x2e, 0x62, 0x69, 0x7a, 0x2e, 0x62, 0x69, 0x72, 0x64, 0x5f, 0x61, 0x69, 0x5f,
	0x73, 0x72, 0x76, 0x2e, 0x62, 0x69, 0x72, 0x64, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42,
	0x69, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x25, 0x2e, 0x62, 0x69, 0x7a,
	0x2e, 0x62, 0x69, 0x72, 0x64, 0x5f, 0x61, 0x69, 0x5f, 0x73, 0x72, 0x76, 0x2e, 0x62, 0x69, 0x72,
	0x64, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x69, 0x72, 0x64, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x12, 0x5c, 0x0a, 0x0a, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x42, 0x69, 0x72, 0x64, 0x12,
	0x27, 0x2e, 0x62, 0x69, 0x7a, 0x2e, 0x62, 0x69, 0x72, 0x64, 0x5f, 0x61, 0x69, 0x5f, 0x73, 0x72,
	0x76, 0x2e, 0x62, 0x69, 0x72, 0x64, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x42, 0x69, 0x72,
	0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x25, 0x2e, 0x62, 0x69, 0x7a, 0x2e, 0x62,
	0x69, 0x72, 0x64, 0x5f, 0x61, 0x69, 0x5f, 0x73, 0x72, 0x76, 0x2e, 0x62, 0x69, 0x72, 0x64, 0x2e,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x42, 0x69, 0x72, 0x64, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12,
	0x5c, 0x0a, 0x0a, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x69, 0x72, 0x64, 0x12, 0x27, 0x2e,
	0x62, 0x69, 0x7a, 0x2e, 0x62, 0x69, 0x72, 0x64, 0x5f, 0x61, 0x69, 0x5f, 0x73, 0x72, 0x76, 0x2e,
	0x62, 0x69, 0x72, 0x64, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x69, 0x72, 0x64, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x25, 0x2e, 0x62, 0x69, 0x7a, 0x2e, 0x62, 0x69, 0x72,
	0x64, 0x5f, 0x61, 0x69, 0x5f, 0x73, 0x72, 0x76, 0x2e, 0x62, 0x69, 0x72, 0x64, 0x2e, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x42, 0x69, 0x72, 0x64, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x53, 0x0a,
	0x07, 0x47, 0x65, 0x74, 0x42, 0x69, 0x72, 0x64, 0x12, 0x24, 0x2e, 0x62, 0x69, 0x7a, 0x2e, 0x62,
	0x69, 0x72, 0x64, 0x5f, 0x61, 0x69, 0x5f, 0x73, 0x72, 0x76, 0x2e, 0x62, 0x69, 0x72, 0x64, 0x2e,
	0x47, 0x65, 0x74, 0x42, 0x69, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22,
	0x2e, 0x62, 0x69, 0x7a, 0x2e, 0x62, 0x69, 0x72, 0x64, 0x5f, 0x61, 0x69, 0x5f, 0x73, 0x72, 0x76,
	0x2e, 0x62, 0x69, 0x72, 0x64, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x69, 0x72, 0x64, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x12, 0x90, 0x01, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x42, 0x69, 0x72, 0x64, 0x44, 0x65,
	0x74, 0x61, 0x69, 0x6c, 0x42, 0x79, 0x49, 0x64, 0x12, 0x2e, 0x2e, 0x62, 0x69, 0x7a, 0x2e, 0x62,
	0x69, 0x72, 0x64, 0x5f, 0x61, 0x69, 0x5f, 0x73, 0x72, 0x76, 0x2e, 0x62, 0x69, 0x72, 0x64, 0x2e,
	0x47, 0x65, 0x74, 0x42, 0x69, 0x72, 0x64, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x42, 0x79, 0x49,
	0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2c, 0x2e, 0x62, 0x69, 0x7a, 0x2e, 0x62,
	0x69, 0x72, 0x64, 0x5f, 0x61, 0x69, 0x5f, 0x73, 0x72, 0x76, 0x2e, 0x62, 0x69, 0x72, 0x64, 0x2e,
	0x47, 0x65, 0x74, 0x42, 0x69, 0x72, 0x64, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x42, 0x79, 0x49,
	0x64, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x1d, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x17, 0x12, 0x15,
	0x79, 0x77, 0x2f, 0x62, 0x69, 0x72, 0x64, 0x2f, 0x67, 0x65, 0x74, 0x42, 0x69, 0x72, 0x64, 0x44,
	0x65, 0x74, 0x61, 0x69, 0x6c, 0x12, 0x70, 0x0a, 0x0d, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x69, 0x72,
	0x64, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x28,
	0x2e, 0x62, 0x69, 0x7a, 0x2e, 0x62, 0x69, 0x72, 0x64, 0x5f, 0x61, 0x69, 0x5f, 0x73, 0x72, 0x76,
	0x2e, 0x62, 0x69, 0x72, 0x64, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x69, 0x72, 0x64, 0x4f, 0x72,
	0x64, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x1d, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x17,
	0x12, 0x15, 0x79, 0x77, 0x2f, 0x62, 0x69, 0x72, 0x64, 0x2f, 0x6c, 0x69, 0x73, 0x74, 0x42, 0x69,
	0x72, 0x64, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x98, 0x01, 0x0a, 0x13, 0x4c, 0x69, 0x73, 0x74,
	0x42, 0x69, 0x72, 0x64, 0x42, 0x61, 0x73, 0x65, 0x42, 0x79, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x12,
	0x30, 0x2e, 0x62, 0x69, 0x7a, 0x2e, 0x62, 0x69, 0x72, 0x64, 0x5f, 0x61, 0x69, 0x5f, 0x73, 0x72,
	0x76, 0x2e, 0x62, 0x69, 0x72, 0x64, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x69, 0x72, 0x64, 0x42,
	0x61, 0x73, 0x65, 0x42, 0x79, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x2e, 0x2e, 0x62, 0x69, 0x7a, 0x2e, 0x62, 0x69, 0x72, 0x64, 0x5f, 0x61, 0x69, 0x5f,
	0x73, 0x72, 0x76, 0x2e, 0x62, 0x69, 0x72, 0x64, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x69, 0x72,
	0x64, 0x42, 0x61, 0x73, 0x65, 0x42, 0x79, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x22, 0x1f, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x19, 0x12, 0x17, 0x79, 0x77, 0x2f, 0x62, 0x69,
	0x72, 0x64, 0x2f, 0x6c, 0x69, 0x73, 0x74, 0x42, 0x61, 0x73, 0x65, 0x42, 0x79, 0x4f, 0x72, 0x64,
	0x65, 0x72, 0x42, 0x30, 0x0a, 0x08, 0x61, 0x70, 0x69, 0x2e, 0x62, 0x69, 0x72, 0x64, 0x50, 0x01,
	0x5a, 0x22, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x52, 0x65, 0x70, 0x6f, 0x2f, 0x70, 0x62, 0x2f, 0x62,
	0x69, 0x72, 0x64, 0x5f, 0x61, 0x69, 0x5f, 0x73, 0x72, 0x76, 0x2f, 0x62, 0x69, 0x72, 0x64, 0x3b,
	0x62, 0x69, 0x72, 0x64, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_bird_ai_srv_bird_bird_Info_proto_rawDescOnce sync.Once
	file_bird_ai_srv_bird_bird_Info_proto_rawDescData = file_bird_ai_srv_bird_bird_Info_proto_rawDesc
)

func file_bird_ai_srv_bird_bird_Info_proto_rawDescGZIP() []byte {
	file_bird_ai_srv_bird_bird_Info_proto_rawDescOnce.Do(func() {
		file_bird_ai_srv_bird_bird_Info_proto_rawDescData = protoimpl.X.CompressGZIP(file_bird_ai_srv_bird_bird_Info_proto_rawDescData)
	})
	return file_bird_ai_srv_bird_bird_Info_proto_rawDescData
}

var file_bird_ai_srv_bird_bird_Info_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_bird_ai_srv_bird_bird_Info_proto_goTypes = []interface{}{
	(*GetBirdDetailByIdRequest)(nil),         // 0: biz.bird_ai_srv.bird.GetBirdDetailByIdRequest
	(*GetBirdDetailByIdReply)(nil),           // 1: biz.bird_ai_srv.bird.GetBirdDetailByIdReply
	(*CreateBirdRequest)(nil),                // 2: biz.bird_ai_srv.bird.CreateBirdRequest
	(*CreateBirdReply)(nil),                  // 3: biz.bird_ai_srv.bird.CreateBirdReply
	(*UpdateBirdRequest)(nil),                // 4: biz.bird_ai_srv.bird.UpdateBirdRequest
	(*UpdateBirdReply)(nil),                  // 5: biz.bird_ai_srv.bird.UpdateBirdReply
	(*DeleteBirdRequest)(nil),                // 6: biz.bird_ai_srv.bird.DeleteBirdRequest
	(*DeleteBirdReply)(nil),                  // 7: biz.bird_ai_srv.bird.DeleteBirdReply
	(*GetBirdRequest)(nil),                   // 8: biz.bird_ai_srv.bird.GetBirdRequest
	(*GetBirdReply)(nil),                     // 9: biz.bird_ai_srv.bird.GetBirdReply
	(*ListBirdOrderReply)(nil),               // 10: biz.bird_ai_srv.bird.ListBirdOrderReply
	(*ListBirdBaseByOrderRequest)(nil),       // 11: biz.bird_ai_srv.bird.ListBirdBaseByOrderRequest
	(*BirdBase)(nil),                         // 12: biz.bird_ai_srv.bird.BirdBase
	(*ListBirdBaseByOrderReply)(nil),         // 13: biz.bird_ai_srv.bird.ListBirdBaseByOrderReply
	(*ListBirdOrderReply_BirdOrderList)(nil), // 14: biz.bird_ai_srv.bird.ListBirdOrderReply.BirdOrderList
	(*page.PageQuery)(nil),                   // 15: page.PageQuery
	(*page.PageInfo)(nil),                    // 16: page.PageInfo
	(*emptypb.Empty)(nil),                    // 17: google.protobuf.Empty
}
var file_bird_ai_srv_bird_bird_Info_proto_depIdxs = []int32{
	14, // 0: biz.bird_ai_srv.bird.ListBirdOrderReply.birdOrderList:type_name -> biz.bird_ai_srv.bird.ListBirdOrderReply.BirdOrderList
	15, // 1: biz.bird_ai_srv.bird.ListBirdBaseByOrderRequest.page:type_name -> page.PageQuery
	16, // 2: biz.bird_ai_srv.bird.ListBirdBaseByOrderReply.page_info:type_name -> page.PageInfo
	12, // 3: biz.bird_ai_srv.bird.ListBirdBaseByOrderReply.list:type_name -> biz.bird_ai_srv.bird.BirdBase
	2,  // 4: biz.bird_ai_srv.bird.BirdInfo.CreateBird:input_type -> biz.bird_ai_srv.bird.CreateBirdRequest
	4,  // 5: biz.bird_ai_srv.bird.BirdInfo.UpdateBird:input_type -> biz.bird_ai_srv.bird.UpdateBirdRequest
	6,  // 6: biz.bird_ai_srv.bird.BirdInfo.DeleteBird:input_type -> biz.bird_ai_srv.bird.DeleteBirdRequest
	8,  // 7: biz.bird_ai_srv.bird.BirdInfo.GetBird:input_type -> biz.bird_ai_srv.bird.GetBirdRequest
	0,  // 8: biz.bird_ai_srv.bird.BirdInfo.GetBirdDetailById:input_type -> biz.bird_ai_srv.bird.GetBirdDetailByIdRequest
	17, // 9: biz.bird_ai_srv.bird.BirdInfo.ListBirdOrder:input_type -> google.protobuf.Empty
	11, // 10: biz.bird_ai_srv.bird.BirdInfo.ListBirdBaseByOrder:input_type -> biz.bird_ai_srv.bird.ListBirdBaseByOrderRequest
	3,  // 11: biz.bird_ai_srv.bird.BirdInfo.CreateBird:output_type -> biz.bird_ai_srv.bird.CreateBirdReply
	5,  // 12: biz.bird_ai_srv.bird.BirdInfo.UpdateBird:output_type -> biz.bird_ai_srv.bird.UpdateBirdReply
	7,  // 13: biz.bird_ai_srv.bird.BirdInfo.DeleteBird:output_type -> biz.bird_ai_srv.bird.DeleteBirdReply
	9,  // 14: biz.bird_ai_srv.bird.BirdInfo.GetBird:output_type -> biz.bird_ai_srv.bird.GetBirdReply
	1,  // 15: biz.bird_ai_srv.bird.BirdInfo.GetBirdDetailById:output_type -> biz.bird_ai_srv.bird.GetBirdDetailByIdReply
	10, // 16: biz.bird_ai_srv.bird.BirdInfo.ListBirdOrder:output_type -> biz.bird_ai_srv.bird.ListBirdOrderReply
	13, // 17: biz.bird_ai_srv.bird.BirdInfo.ListBirdBaseByOrder:output_type -> biz.bird_ai_srv.bird.ListBirdBaseByOrderReply
	11, // [11:18] is the sub-list for method output_type
	4,  // [4:11] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_bird_ai_srv_bird_bird_Info_proto_init() }
func file_bird_ai_srv_bird_bird_Info_proto_init() {
	if File_bird_ai_srv_bird_bird_Info_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_bird_ai_srv_bird_bird_Info_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBirdDetailByIdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bird_ai_srv_bird_bird_Info_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBirdDetailByIdReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bird_ai_srv_bird_bird_Info_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateBirdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bird_ai_srv_bird_bird_Info_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateBirdReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bird_ai_srv_bird_bird_Info_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateBirdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bird_ai_srv_bird_bird_Info_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateBirdReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bird_ai_srv_bird_bird_Info_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteBirdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bird_ai_srv_bird_bird_Info_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteBirdReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bird_ai_srv_bird_bird_Info_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBirdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bird_ai_srv_bird_bird_Info_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBirdReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bird_ai_srv_bird_bird_Info_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListBirdOrderReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bird_ai_srv_bird_bird_Info_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListBirdBaseByOrderRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bird_ai_srv_bird_bird_Info_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BirdBase); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bird_ai_srv_bird_bird_Info_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListBirdBaseByOrderReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bird_ai_srv_bird_bird_Info_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListBirdOrderReply_BirdOrderList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_bird_ai_srv_bird_bird_Info_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bird_ai_srv_bird_bird_Info_proto_goTypes,
		DependencyIndexes: file_bird_ai_srv_bird_bird_Info_proto_depIdxs,
		MessageInfos:      file_bird_ai_srv_bird_bird_Info_proto_msgTypes,
	}.Build()
	File_bird_ai_srv_bird_bird_Info_proto = out.File
	file_bird_ai_srv_bird_bird_Info_proto_rawDesc = nil
	file_bird_ai_srv_bird_bird_Info_proto_goTypes = nil
	file_bird_ai_srv_bird_bird_Info_proto_depIdxs = nil
}
